//! Reference-implementation parity tests.
//!
//! These tests read CSV "golden" files that were generated by standalone
//! C++ extractions of authoritative reference math (see
//! `reference-checks/` at the crate root) and verify that zentone's own
//! implementations reproduce the same outputs within a tight f32
//! tolerance.
//!
//! Current coverage:
//! - libultrahdr `ReinhardMap` (extended Reinhard) → `zentone::reinhard_extended`
//! - libultrahdr `globalTonemap` (max-channel extended Reinhard composition)
//!   → a local helper that calls `zentone::reinhard_extended` the same way
//!
//! The `libultrahdr_apply_gain` and `libultrahdr_compute_gain` golden files
//! are committed for future use in a reference-parity test inside
//! `ultrahdr-core`, which owns the gain-map application and encode math.
//! Zentone itself does not implement those and shouldn't — it's a tone
//! mapping crate, not a gain map codec.
//!
//! See `reference-checks/README.md` for the full story.

use std::fs;
use std::path::PathBuf;

use zentone::reinhard_extended;

/// f32 absolute-error tolerance. ~8× the ulp at 1.0, generous enough to
/// absorb a reordered multiply/divide but tight enough to catch any real
/// formula divergence.
const TOLERANCE: f32 = 1e-6;

fn golden_path(name: &str) -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("reference-checks");
    p.push("golden");
    p.push(name);
    p
}

fn read_csv(name: &str) -> String {
    let path = golden_path(name);
    fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "failed to read golden {}: {e}. Did you run reference-checks/build.sh?",
            path.display()
        )
    })
}

/// Iterate over non-empty, non-comment lines after the CSV header.
/// Splits each line on ','. Skips lines that start with '#' (comments).
fn parse_rows<'a>(body: &'a str, header_prefix: &str) -> impl Iterator<Item = Vec<&'a str>> {
    body.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .skip_while(move |line| !line.starts_with(header_prefix))
        .skip(1) // the header line itself
        .take_while(|line| !line.starts_with('#') && !line.is_empty())
        .map(|line| line.split(',').map(str::trim).collect())
}

/// libultrahdr's globalTonemap, faithfully reimplemented with zentone's
/// `reinhard_extended` as the scalar kernel. Matches the logic in
/// `lib/src/jpegr.cpp:1823` — max channel through ReinhardMap, then scale
/// all channels by the resulting ratio.
fn global_tonemap(rgb_in: [f32; 3], headroom: f32, is_normalized: bool) -> [f32; 3] {
    let rgb_hdr = if is_normalized {
        [
            rgb_in[0] * headroom,
            rgb_in[1] * headroom,
            rgb_in[2] * headroom,
        ]
    } else {
        rgb_in
    };
    let max_hdr = rgb_hdr[0].max(rgb_hdr[1]).max(rgb_hdr[2]);
    let max_sdr = reinhard_extended(max_hdr, headroom);
    if max_hdr <= 0.0 {
        return [0.0, 0.0, 0.0];
    }
    let scale = max_sdr / max_hdr;
    [
        if rgb_hdr[0] > 0.0 {
            rgb_hdr[0] * scale
        } else {
            0.0
        },
        if rgb_hdr[1] > 0.0 {
            rgb_hdr[1] * scale
        } else {
            0.0
        },
        if rgb_hdr[2] > 0.0 {
            rgb_hdr[2] * scale
        } else {
            0.0
        },
    ]
}

#[test]
fn reinhard_map_scalar_matches_libultrahdr() {
    let csv = read_csv("libultrahdr_reinhard.csv");

    let mut checked = 0;
    for cols in parse_rows(&csv, "headroom,y_hdr,y_sdr") {
        if cols.len() != 3 {
            continue;
        }
        let h: f32 = cols[0].parse().unwrap();
        let y: f32 = cols[1].parse().unwrap();
        let expected: f32 = cols[2].parse().unwrap();
        let actual = reinhard_extended(y, h);
        let err = (actual - expected).abs();
        assert!(
            err < TOLERANCE,
            "ReinhardMap mismatch at headroom={h}, y={y}: zentone={actual}, libultrahdr={expected}, err={err}"
        );
        checked += 1;
    }
    assert!(checked > 0, "no rows parsed — CSV format regression?");
    println!("reinhard_map_scalar: checked {checked} rows");
}

#[test]
fn global_tonemap_matches_libultrahdr() {
    let csv = read_csv("libultrahdr_reinhard.csv");

    let mut checked = 0;
    for cols in parse_rows(&csv, "headroom,r_in,g_in,b_in,r_out,g_out,b_out") {
        if cols.len() != 7 {
            continue;
        }
        let h: f32 = cols[0].parse().unwrap();
        let rgb_in = [
            cols[1].parse::<f32>().unwrap(),
            cols[2].parse::<f32>().unwrap(),
            cols[3].parse::<f32>().unwrap(),
        ];
        let expected = [
            cols[4].parse::<f32>().unwrap(),
            cols[5].parse::<f32>().unwrap(),
            cols[6].parse::<f32>().unwrap(),
        ];
        let actual = global_tonemap(rgb_in, h, true);
        for i in 0..3 {
            let err = (actual[i] - expected[i]).abs();
            assert!(
                err < TOLERANCE,
                "globalTonemap mismatch at headroom={h}, rgb_in={rgb_in:?}, channel={i}: zentone={}, libultrahdr={}, err={err}",
                actual[i],
                expected[i]
            );
        }
        checked += 1;
    }
    assert!(checked > 0, "no globalTonemap rows parsed");
    println!("global_tonemap: checked {checked} rows");
}
