//! Reference-implementation parity tests.
//!
//! These tests read CSV "golden" files that were generated by standalone
//! C++ extractions of authoritative reference math (see
//! `reference-checks/` at the crate root) and verify that zentone's own
//! implementations reproduce the same outputs within a tight f32
//! tolerance.
//!
//! Current coverage:
//! - libultrahdr `ReinhardMap` (extended Reinhard) → `zentone::curves::reinhard_extended`
//! - libultrahdr `globalTonemap` (max-channel extended Reinhard composition)
//!   → a local helper that calls `zentone::curves::reinhard_extended` the same way
//!
//! The `libultrahdr_apply_gain` and `libultrahdr_compute_gain` golden files
//! are committed for future use in a reference-parity test inside
//! `ultrahdr-core`, which owns the gain-map application and encode math.
//! Zentone itself does not implement those and shouldn't — it's a tone
//! mapping crate, not a gain map codec.
//!
//! See `reference-checks/README.md` for the full story.

use std::fs;
use std::path::PathBuf;

use zentone::curves::{bt2390_tonemap, bt2390_tonemap_ext, reinhard_extended};
use zentone::{Bt2408Tonemapper, CompiledFilmicSpline, FilmicSplineConfig, LUMA_BT709, ToneMap};

/// f32 absolute-error tolerance. ~8× the ulp at 1.0, generous enough to
/// absorb a reordered multiply/divide but tight enough to catch any real
/// formula divergence.
const TOLERANCE: f32 = 1e-6;

/// Wider tolerance for PQ-domain comparisons. The PQ OETF/EOTF involve
/// `powf` with fractional exponents, where libm and the C++ stdlib can
/// diverge by 1–3 ULP per call. A full EETF pipeline has 4 `powf` calls
/// (2× OETF + 2× EOTF), so the cumulative error can reach ~1e-4 at
/// extreme luminance values where PQ's slope is steep.
const PQ_TOLERANCE: f32 = 5e-4;

fn golden_path(name: &str) -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("reference-checks");
    p.push("golden");
    p.push(name);
    p
}

fn read_csv(name: &str) -> String {
    let path = golden_path(name);
    fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "failed to read golden {}: {e}. Did you run reference-checks/build.sh?",
            path.display()
        )
    })
}

/// Iterate data rows in a specific CSV section. Finds the header line
/// matching `header_prefix`, then yields parsed rows until it hits an
/// empty line, a comment line, or another header-like line (one that
/// doesn't start with a digit, '-', or '+'). This correctly handles
/// multi-section CSV files separated by blank lines and comments.
fn parse_rows<'a>(body: &'a str, header_prefix: &str) -> impl Iterator<Item = Vec<&'a str>> {
    let mut in_section = false;
    let mut past_header = false;
    body.lines().map(str::trim).filter_map(move |line| {
        if !in_section {
            if line.starts_with(header_prefix) {
                in_section = true;
                past_header = false;
            }
            return None;
        }
        if !past_header {
            past_header = true;
            return None; // skip the header line itself
        }
        // Stop at section boundary: blank line or comment line
        if line.is_empty() || line.starts_with('#') {
            in_section = false;
            return None;
        }
        Some(line.split(',').map(str::trim).collect())
    })
}

/// libultrahdr's globalTonemap, faithfully reimplemented with zentone's
/// `reinhard_extended` as the scalar kernel. Matches the logic in
/// `lib/src/jpegr.cpp:1823` — max channel through ReinhardMap, then scale
/// all channels by the resulting ratio.
fn global_tonemap(rgb_in: [f32; 3], headroom: f32, is_normalized: bool) -> [f32; 3] {
    let rgb_hdr = if is_normalized {
        [
            rgb_in[0] * headroom,
            rgb_in[1] * headroom,
            rgb_in[2] * headroom,
        ]
    } else {
        rgb_in
    };
    let max_hdr = rgb_hdr[0].max(rgb_hdr[1]).max(rgb_hdr[2]);
    let max_sdr = reinhard_extended(max_hdr, headroom);
    if max_hdr <= 0.0 {
        return [0.0, 0.0, 0.0];
    }
    let scale = max_sdr / max_hdr;
    [
        if rgb_hdr[0] > 0.0 {
            rgb_hdr[0] * scale
        } else {
            0.0
        },
        if rgb_hdr[1] > 0.0 {
            rgb_hdr[1] * scale
        } else {
            0.0
        },
        if rgb_hdr[2] > 0.0 {
            rgb_hdr[2] * scale
        } else {
            0.0
        },
    ]
}

#[test]
fn reinhard_map_scalar_matches_libultrahdr() {
    let csv = read_csv("libultrahdr_reinhard.csv");

    let mut checked = 0;
    for cols in parse_rows(&csv, "headroom,y_hdr,y_sdr") {
        if cols.len() != 3 {
            continue;
        }
        let h: f32 = cols[0].parse().unwrap();
        let y: f32 = cols[1].parse().unwrap();
        let expected: f32 = cols[2].parse().unwrap();
        let actual = reinhard_extended(y, h);
        let err = (actual - expected).abs();
        assert!(
            err < TOLERANCE,
            "ReinhardMap mismatch at headroom={h}, y={y}: zentone={actual}, libultrahdr={expected}, err={err}"
        );
        checked += 1;
    }
    assert!(checked > 0, "no rows parsed — CSV format regression?");
    println!("reinhard_map_scalar: checked {checked} rows");
}

#[test]
fn global_tonemap_matches_libultrahdr() {
    let csv = read_csv("libultrahdr_reinhard.csv");

    let mut checked = 0;
    for cols in parse_rows(&csv, "headroom,r_in,g_in,b_in,r_out,g_out,b_out") {
        if cols.len() != 7 {
            continue;
        }
        let h: f32 = cols[0].parse().unwrap();
        let rgb_in = [
            cols[1].parse::<f32>().unwrap(),
            cols[2].parse::<f32>().unwrap(),
            cols[3].parse::<f32>().unwrap(),
        ];
        let expected = [
            cols[4].parse::<f32>().unwrap(),
            cols[5].parse::<f32>().unwrap(),
            cols[6].parse::<f32>().unwrap(),
        ];
        let actual = global_tonemap(rgb_in, h, true);
        for i in 0..3 {
            let err = (actual[i] - expected[i]).abs();
            assert!(
                err < TOLERANCE,
                "globalTonemap mismatch at headroom={h}, rgb_in={rgb_in:?}, channel={i}: zentone={}, libultrahdr={}, err={err}",
                actual[i],
                expected[i]
            );
        }
        checked += 1;
    }
    assert!(checked > 0, "no globalTonemap rows parsed");
    println!("global_tonemap: checked {checked} rows");
}

// ============================================================================
// BT.2390 / BT.2408 parity against libplacebo
// ============================================================================

/// Test zentone's Bt2408Tonemapper::tonemap_nits against libplacebo's
/// PQ-domain BT.2390 EETF at knee_offset=0.5 (the ITU standard value,
/// which gives KS = 1.5*maxLum - 0.5, matching zentone's formula).
///
/// Uses PQ_TOLERANCE because the full pipeline involves 4× powf calls
/// through the PQ transfer function.
#[test]
fn bt2408_tonemap_nits_matches_libplacebo_pq() {
    let csv = read_csv("libplacebo_bt2390.csv");

    let mut checked = 0;
    let mut max_err: f32 = 0.0;

    for cols in parse_rows(
        &csv,
        "content_nits,display_nits,knee_offset,input_nits,output_linear",
    ) {
        if cols.len() != 5 {
            continue;
        }
        let content: f32 = cols[0].parse().unwrap();
        let display: f32 = cols[1].parse().unwrap();
        let offset: f32 = cols[2].parse().unwrap();
        let input_nits: f32 = cols[3].parse().unwrap();
        let expected_nits: f32 = cols[4].parse().unwrap();

        // Only test knee_offset=0.5 rows (the ITU standard zentone implements).
        // knee_offset=1.0 is libplacebo's default but a different formula.
        if (offset - 0.5).abs() > 0.01 {
            continue;
        }

        // Skip passthrough configs (content <= display)
        if content <= display {
            continue;
        }

        let tm = Bt2408Tonemapper::with_luma(content, display, LUMA_BT709);
        let actual_nits = tm.tonemap_nits(input_nits);

        // Use relative tolerance for large values, absolute for small
        let err = (actual_nits - expected_nits).abs();
        let rel = if expected_nits.abs() > 1.0 {
            err / expected_nits.abs()
        } else {
            err
        };

        max_err = max_err.max(rel);

        assert!(
            rel < PQ_TOLERANCE,
            "BT.2408 mismatch: content={content}, display={display}, \
             input={input_nits} nits: zentone={actual_nits}, \
             libplacebo={expected_nits}, rel_err={rel}"
        );
        checked += 1;
    }
    assert!(checked > 10, "too few PQ-domain rows checked: {checked}");
    println!("bt2408_tonemap_nits: checked {checked} rows, max_rel_err={max_err:.6e}");
}

/// Test zentone's bt2390_tonemap and bt2390_tonemap_ext against
/// libplacebo's scene-linear BT.2390 EETF. This is an exact comparison
/// (no PQ conversion involved), so we use tight tolerance.
#[test]
fn bt2390_scene_linear_matches_libplacebo() {
    let csv = read_csv("libplacebo_bt2390.csv");

    let mut checked = 0;
    let mut max_err: f32 = 0.0;

    for cols in parse_rows(&csv, "source_peak,target_peak,min_lum,input,output") {
        if cols.len() != 5 {
            continue;
        }
        let source: f32 = cols[0].parse().unwrap();
        let target: f32 = cols[1].parse().unwrap();
        let min_lum: f32 = cols[2].parse().unwrap();
        let input: f32 = cols[3].parse().unwrap();
        let expected: f32 = cols[4].parse().unwrap();

        let actual = if min_lum > 0.0 {
            bt2390_tonemap_ext(input, source, target, Some(min_lum))
        } else {
            bt2390_tonemap(input, source, target)
        };

        let err = (actual - expected).abs();
        max_err = max_err.max(err);

        assert!(
            err < TOLERANCE,
            "bt2390 scene-linear mismatch: source={source}, target={target}, \
             min_lum={min_lum}, input={input}: zentone={actual}, \
             libplacebo={expected}, err={err}"
        );
        checked += 1;
    }
    assert!(checked > 20, "too few scene-linear rows checked: {checked}");
    println!("bt2390_scene_linear: checked {checked} rows, max_err={max_err:.6e}");
}

// ============================================================================
// darktable filmic spline parity
// ============================================================================

/// Make a FilmicSplineConfig matching the named darktable golden config.
fn filmic_config(name: &str) -> FilmicSplineConfig {
    let mut cfg = FilmicSplineConfig::default();
    match name {
        "zentone_defaults" => {}
        "darktable_defaults" => {
            cfg.output_power = 4.0;
            cfg.latitude = 0.01;
            cfg.white_point_source = 4.0;
            cfg.contrast = 1.0;
        }
        "high_contrast" => {
            cfg.contrast = 2.5;
        }
        "with_saturation" => {
            cfg.saturation = 50.0;
        }
        _ => panic!("unknown config: {name}"),
    }
    cfg
}

/// Test CompiledFilmicSpline::map_rgb against darktable's filmic_rgb
/// output at multiple parameter configurations and RGB inputs.
#[test]
fn filmic_spline_matches_darktable_rgb() {
    let csv = read_csv("darktable_filmic.csv");
    let mut checked = 0;
    let mut max_err: f32 = 0.0;

    for cols in parse_rows(&csv, "config,r_in,g_in,b_in,r_out,g_out,b_out") {
        if cols.len() != 7 {
            continue;
        }
        let config_name = cols[0];
        let rgb_in = [
            cols[1].parse::<f32>().unwrap(),
            cols[2].parse::<f32>().unwrap(),
            cols[3].parse::<f32>().unwrap(),
        ];
        let expected = [
            cols[4].parse::<f32>().unwrap(),
            cols[5].parse::<f32>().unwrap(),
            cols[6].parse::<f32>().unwrap(),
        ];

        let cfg = filmic_config(config_name);
        let spline = CompiledFilmicSpline::new(&cfg);
        let actual = spline.map_rgb(rgb_in);

        for i in 0..3 {
            let err = (actual[i] - expected[i]).abs();
            max_err = max_err.max(err);
            assert!(
                err < 1e-4,
                "filmic {config_name} at {rgb_in:?}[{i}]: zentone={}, darktable={}, err={err}",
                actual[i],
                expected[i]
            );
        }
        checked += 1;
    }
    assert!(checked > 20, "too few filmic RGB rows: {checked}");
    println!("filmic_spline_rgb: checked {checked} rows, max_err={max_err:.6e}");
}

/// Test the raw spline evaluation (apply_spline) against darktable's
/// filmic_spline at multiple x values.
#[test]
fn filmic_spline_eval_matches_darktable() {
    let csv = read_csv("darktable_filmic.csv");
    let mut checked = 0;
    let mut max_err: f32 = 0.0;

    for cols in parse_rows(&csv, "config,x,spline_y") {
        if cols.len() != 3 {
            continue;
        }
        let config_name = cols[0];
        let x: f32 = cols[1].parse().unwrap();
        let expected: f32 = cols[2].parse().unwrap();

        let cfg = filmic_config(config_name);
        let spline = CompiledFilmicSpline::new(&cfg);
        let actual = spline.apply_spline(x);

        let err = (actual - expected).abs();
        max_err = max_err.max(err);
        assert!(
            err < 1e-4,
            "filmic spline {config_name} at x={x}: zentone={actual}, darktable={expected}, err={err}"
        );
        checked += 1;
    }
    assert!(checked > 20, "too few spline eval rows: {checked}");
    println!("filmic_spline_eval: checked {checked} rows, max_err={max_err:.6e}");
}
