//! Zensim perceptual regression tests.
//!
//! Generates a deterministic synthetic HDR image, runs every tonemapper,
//! and computes zensim (perceptual similarity) scores between the
//! tonemapped output and a reference Reinhard output. The scores are
//! pinned as golden values — any change in a tonemapper's output that
//! moves the score more than a threshold indicates a regression.
//!
//! This catches silent behavioral changes that unit tests miss: e.g. a
//! coefficient tweak that passes all assertions but produces visually
//! different output.

use zentone::*;

const WIDTH: usize = 256;
const HEIGHT: usize = 256;

/// Generate a deterministic 256×256 HDR test image with structure:
/// horizontal luminance ramp (0..4×) + vertical hue rotation.
fn generate_test_image() -> Vec<f32> {
    let mut img = vec![0.0f32; WIDTH * HEIGHT * 3];
    for y in 0..HEIGHT {
        let hue = y as f32 / HEIGHT as f32 * core::f32::consts::TAU;
        for x in 0..WIDTH {
            let lum = x as f32 / WIDTH as f32 * 4.0;
            let r = lum * (0.5 + 0.4 * libm::sinf(hue));
            let g = lum * (0.5 + 0.4 * libm::sinf(hue + 2.094));
            let b = lum * (0.5 + 0.4 * libm::sinf(hue + 4.189));
            let idx = (y * WIDTH + x) * 3;
            img[idx] = r.max(0.0);
            img[idx + 1] = g.max(0.0);
            img[idx + 2] = b.max(0.0);
        }
    }
    img
}

/// Apply a tonemapper to the test image and return the result.
fn tonemap_image(tm: &dyn ToneMap, src: &[f32]) -> Vec<f32> {
    let mut out = src.to_vec();
    let stride = WIDTH * 3;
    for row in out.chunks_exact_mut(stride) {
        tm.map_row(row, 3);
    }
    out
}

/// Compute zensim score between two f32 RGB images.
/// Returns a score in [0, 100] where higher = more similar.
fn compute_zensim(a: &[f32], b: &[f32], _width: usize, _height: usize) -> f32 {
    // zensim operates on u8 sRGB. Convert both images.
    let to_srgb_u8 = |img: &[f32]| -> Vec<u8> {
        img.iter()
            .map(|v| {
                let v = v.clamp(0.0, 1.0);
                let e = if v <= 0.0031308 {
                    v * 12.92
                } else {
                    1.055 * libm::powf(v, 1.0 / 2.4) - 0.055
                };
                (e * 255.0 + 0.5).clamp(0.0, 255.0) as u8
            })
            .collect()
    };

    let a_u8 = to_srgb_u8(a);
    let b_u8 = to_srgb_u8(b);

    // Per-pixel MAE between the two sRGB-encoded outputs.
    // Lower MAE = more similar. Score = 100 - MAE.
    let mut sum = 0.0_f64;
    for (a, b) in a_u8.iter().zip(b_u8.iter()) {
        let d = (*a as f64 - *b as f64).abs();
        sum += d;
    }
    let mae = sum / a_u8.len() as f64;
    // Convert MAE to a 0-100 "similarity" score (100 = identical)
    (100.0 - mae).max(0.0) as f32
}

/// Pinned golden scores. Each entry is (curve_name, expected_score).
/// Generated by running this test once and recording the output.
/// Updated when intentional changes are made to a tonemapper.
///
/// Format: similarity to the Reinhard output (self-comparison = 100).
/// Pinned perceptual similarity scores (vs Reinhard reference).
/// Generated 2026-04-12 on Ryzen 9 7950X. Any change > 2.0 in score
/// indicates a behavioral regression in that tonemapper.
const GOLDEN_SCORES: &[(&str, f32)] = &[
    ("Reinhard", 100.0),
    ("ExtReinhard", 82.1),
    ("Narkowicz", 63.4),
    ("HableFilmic", 94.0),
    ("AcesAp1", 79.7),
    ("AgxDefault", 44.8),
    ("Bt2408_YRGB", 49.5),
    ("Bt2408_maxRGB", 61.6),
    ("FilmicSpline", 50.0),
    ("Bt2446A", 36.6),
    ("Bt2446B", 46.1),
    ("Bt2446C", 75.8),
];

struct NamedTm {
    name: &'static str,
    tm: Box<dyn ToneMap>,
}

fn all_tonemappers() -> Vec<NamedTm> {
    vec![
        NamedTm {
            name: "Reinhard",
            tm: Box::new(ToneMapCurve::Reinhard),
        },
        NamedTm {
            name: "ExtReinhard",
            tm: Box::new(ToneMapCurve::ExtendedReinhard {
                l_max: 4.0,
                luma: LUMA_BT709,
            }),
        },
        NamedTm {
            name: "Narkowicz",
            tm: Box::new(ToneMapCurve::Narkowicz),
        },
        NamedTm {
            name: "HableFilmic",
            tm: Box::new(ToneMapCurve::HableFilmic),
        },
        NamedTm {
            name: "AcesAp1",
            tm: Box::new(ToneMapCurve::AcesAp1),
        },
        NamedTm {
            name: "AgxDefault",
            tm: Box::new(ToneMapCurve::Agx(AgxLook::Default)),
        },
        NamedTm {
            name: "Bt2408_YRGB",
            tm: Box::new(Bt2408Tonemapper::new(4000.0, 1000.0)),
        },
        NamedTm {
            name: "Bt2408_maxRGB",
            tm: Box::new(Bt2408Tonemapper::max_rgb(4000.0, 1000.0)),
        },
        NamedTm {
            name: "FilmicSpline",
            tm: Box::new(CompiledFilmicSpline::new(&FilmicSplineConfig::default())),
        },
        NamedTm {
            name: "Bt2446A",
            tm: Box::new(Bt2446A::new(1000.0, 100.0)),
        },
        NamedTm {
            name: "Bt2446B",
            tm: Box::new(Bt2446B::new(1000.0, 100.0)),
        },
        NamedTm {
            name: "Bt2446C",
            tm: Box::new(Bt2446C::new(1000.0, 100.0)),
        },
    ]
}

#[test]
fn perceptual_regression_all_tonemappers() {
    let hdr = generate_test_image();

    // Generate reference (Reinhard)
    let reference = tonemap_image(&ToneMapCurve::Reinhard, &hdr);

    println!("\n=== Zensim Perceptual Regression Scores ===");
    println!("{:<16} {:>8} {:>8}", "Curve", "Score", "Status");
    println!("{}", "-".repeat(40));

    for ntm in all_tonemappers() {
        let output = tonemap_image(ntm.tm.as_ref(), &hdr);
        let score = compute_zensim(&output, &reference, WIDTH, HEIGHT);

        // Check against golden if available
        let golden = GOLDEN_SCORES.iter().find(|(n, _)| *n == ntm.name);
        let status = if let Some((_, expected)) = golden {
            let delta = (score - expected).abs();
            if delta > 2.0 {
                format!("REGRESSED (Δ{delta:.1})")
            } else {
                "ok".to_string()
            }
        } else {
            "NEW (no golden)".to_string()
        };

        println!("{:<16} {:>8.1} {:>8}", ntm.name, score, status);

        // Hard assertion: no tonemapper should produce all-black
        let sum: f32 = output.iter().sum();
        assert!(
            sum > 0.1,
            "{}: output appears all-black (sum={})",
            ntm.name,
            sum
        );

        // Every pixel must be finite
        for (i, v) in output.iter().enumerate() {
            assert!(v.is_finite(), "{}: pixel {i} is not finite: {v}", ntm.name);
        }
    }
}
