#!/usr/bin/env python3
"""Generate ACES encoding / display goldens from OpenColorIO.

Companion to `aces2_ocio_reference.py` (which covers the ACES 2.0 rendering
stages). This script covers the pieces around the rendering that zentone also
ports from the Academy CTL and the ACES specs:

  aces2_ocio_display_encoding.csv   ACES2065-1 -> display code values through
                                    the ACES 2.0 output transform *plus* the
                                    display encoding (`Lib.Academy.DisplayEncoding.ctl`):
                                    peak clamp, white scaling for D60 limiting,
                                    limiting->encoding primaries, inverse EOTF.
                                    Built from OCIO's `ACES-OUTPUT - ..._2.0`
                                    builtins composed with its `DISPLAY -` builtins.
  aces_ocio_acescct.csv             ACEScct / ACEScc log encodings (S-2016-001 /
                                    S-2014-003): linear AP1 <-> log AP1.
  aces_ocio_rgc13.csv               ACES 1.3 Reference Gamut Compression
                                    (FIXED_FUNCTION_ACES_GAMUT_COMP_13), fwd + inv.
  aces_ocio_cdl.csv                 ASC CDL (slope / offset / power / saturation),
                                    ASC (clamping) and no-clamp styles, fwd + inv.

Usage (needs `opencolorio` and `numpy`; e.g. `uv pip install opencolorio numpy`):

    python3 reference-checks/aces_ocio_encodings_reference.py

Deterministic (fixed RNG seed): re-running regenerates byte-identical files
for the same OCIO version.
"""

import os
import random

import numpy as np
import PyOpenColorIO as ocio

HERE = os.path.dirname(os.path.abspath(__file__))
GOLDEN = os.path.join(HERE, "golden")

CFG = ocio.Config.CreateRaw()


def run(transform, rows, inverse=False):
    if inverse:
        transform = transform.createEditableCopy() if hasattr(transform, "createEditableCopy") else transform
        transform.setDirection(ocio.TRANSFORM_DIR_INVERSE)
    cpu = CFG.getProcessor(transform).getDefaultCPUProcessor()
    a = np.array(rows, dtype=np.float32).reshape(-1, 3).copy()
    cpu.applyRGB(a)
    return a


def group(*transforms):
    g = ocio.GroupTransform()
    for t in transforms:
        g.appendTransform(t)
    return g


def builtin(style):
    return ocio.BuiltinTransform(style=style)


def fmt(v):
    return str(np.float32(v))


def write_csv(name, header_lines, rows):
    path = os.path.join(GOLDEN, name)
    with open(path, "w") as f:
        f.write(
            f"# generated by reference-checks/aces_ocio_encodings_reference.py, OpenColorIO {ocio.__version__}\n"
        )
        for h in header_lines:
            f.write(f"# {h}\n")
        for row in rows:
            f.write(",".join(row) + "\n")
    print(f"wrote {path} ({len(rows)} rows)")


def scene_samples(rng):
    """Scene-linear AP0 triples: greys, primaries at several exposures, random."""
    out = []
    for g in [0.0, 1e-4, 1e-3, 0.01, 0.05, 0.18, 0.5, 1.0, 2.0, 8.0, 32.0, 100.0]:
        out.append([g, g, g])
    corners = [[1, 0, 0], [1, 1, 0], [0, 1, 0], [0, 1, 1], [0, 0, 1], [1, 0, 1]]
    for scale in [0.05, 0.5, 1.0, 10.0]:
        for c in corners:
            out.append([scale * v for v in c])
    for _ in range(30):
        lum = 10 ** rng.uniform(-3, 2)
        r, g, b = (rng.uniform(0.05, 1.0) for _ in range(3))
        m = max(r, g, b)
        out.append([lum * r / m, lum * g / m, lum * b / m])
    for _ in range(8):
        out.append([rng.uniform(-0.05, 0.3), rng.uniform(-0.05, 0.3), rng.uniform(-0.05, 0.3)])
    return out


# (zentone preset name, OCIO ACES-OUTPUT 2.0 builtin, OCIO DISPLAY builtin)
DISPLAY_PRESETS = [
    ("rec709_100_srgb", "SDR-100nit-REC709_2.0", "DISPLAY - CIE-XYZ-D65_to_sRGB"),
    ("rec709_100_bt1886", "SDR-100nit-REC709_2.0", "DISPLAY - CIE-XYZ-D65_to_REC.1886-REC.709"),
    ("rec709_100_g22", "SDR-100nit-REC709_2.0", "DISPLAY - CIE-XYZ-D65_to_G2.2-REC.709"),
    ("p3d65_100_g26", "SDR-100nit-P3-D65_2.0", "DISPLAY - CIE-XYZ-D65_to_G2.6-P3-D65"),
    ("p3d65_1000_pq", "HDR-1000nit-P3-D65_2.0", "DISPLAY - CIE-XYZ-D65_to_ST2084-P3-D65"),
    ("rec2020_1000_pq", "HDR-1000nit-REC2020_2.0", "DISPLAY - CIE-XYZ-D65_to_REC.2100-PQ"),
    ("p3d65_1000_hlg_rec2100", "HDR-1000nit-P3-D65_2.0", "DISPLAY - CIE-XYZ-D65_to_REC.2100-HLG-1000nit"),
    ("rec709d60_100_srgb", "SDR-100nit-REC709-D60-in-REC709-D65_2.0", "DISPLAY - CIE-XYZ-D65_to_sRGB"),
    ("p3d60_1000_pq_rec2100", "HDR-1000nit-P3-D60-in-REC2020-D65_2.0", "DISPLAY - CIE-XYZ-D65_to_REC.2100-PQ"),
]


def display_encoding(rng, samples):
    # Every third sample keeps each golden under the repo's 30 KB file cap.
    samples = samples[::3]
    rows = []
    inv_rows = []
    for name, ot, disp in DISPLAY_PRESETS:
        t = group(builtin(f"ACES-OUTPUT - ACES2065-1_to_CIE-XYZ-D65 - {ot}"), builtin(disp))
        cv = run(t, samples)
        for rgb, c in zip(samples, cv):
            rows.append([name] + [fmt(v) for v in rgb] + [fmt(v) for v in c])
        back = run(t, cv, inverse=True)
        for c, a in zip(cv, back):
            inv_rows.append([name] + [fmt(v) for v in c] + [fmt(v) for v in a])
    write_csv(
        "aces2_ocio_display_encoding.csv",
        [
            "ACES-OUTPUT - ACES2065-1_to_CIE-XYZ-D65 - <preset>_2.0 followed by DISPLAY - CIE-XYZ-D65_to_<encoding>",
            "columns: preset,r_ap0,g_ap0,b_ap0,cv_r,cv_g,cv_b",
            "presets: " + "; ".join(f"{n} = {ot} + {d}" for n, ot, d in DISPLAY_PRESETS),
        ],
        rows,
    )
    write_csv(
        "aces2_ocio_display_encoding_inv.csv",
        [
            "inverse of aces2_ocio_display_encoding.csv (display code values -> ACES2065-1)",
            "columns: preset,cv_r,cv_g,cv_b,r_ap0,g_ap0,b_ap0",
        ],
        inv_rows,
    )


def acescct(rng):
    # Linear AP1 values spanning the log curves' domains, including the
    # ACEScct linear toe region (< 0.0078125) and negatives (ACEScct encodes
    # them linearly; ACEScc clamps below 2^-16 and encodes negatives specially).
    lin = [0.0, 1e-6, 1e-5, 1e-4, 1e-3, 0.0078125, 0.01, 0.05, 0.18, 0.5, 1.0, 2.0, 8.0, 32.0, 65504.0]
    lin += [-1e-4, -0.01, -0.1, -1.0]
    lin += [10 ** rng.uniform(-6, 4.8) for _ in range(40)]
    rows3 = [[v, v * 0.5, v * 0.25] for v in lin]
    cct = run(builtin("CURVE - ACEScct-LOG_to_LINEAR"), rows3, inverse=True)
    rows = []
    for a, b in zip(rows3, cct):
        rows.append(["acescct"] + [fmt(v) for v in a] + [fmt(v) for v in b])
    # ACEScc has no bare-curve builtin; ACEScc_to_ACES2065-1 is curve + AP1->AP0.
    # Golden the full path (log AP1 -> linear AP0) in both directions.
    ap0 = run(builtin("ACEScct_to_ACES2065-1"), cct)
    for a, b in zip(cct, ap0):
        rows.append(["acescct_to_ap0"] + [fmt(v) for v in a] + [fmt(v) for v in b])
    log_cc = run(builtin("ACEScc_to_ACES2065-1"), ap0, inverse=True)
    for a, b in zip(ap0, log_cc):
        rows.append(["ap0_to_acescc"] + [fmt(v) for v in a] + [fmt(v) for v in b])
    ap0_back = run(builtin("ACEScc_to_ACES2065-1"), log_cc)
    for a, b in zip(log_cc, ap0_back):
        rows.append(["acescc_to_ap0"] + [fmt(v) for v in a] + [fmt(v) for v in b])
    write_csv(
        "aces_ocio_acescct.csv",
        [
            "ACEScct / ACEScc (S-2016-001 / S-2014-003)",
            "columns: kind,in_r,in_g,in_b,out_r,out_g,out_b",
            "acescct: linear AP1 -> ACEScct (CURVE - ACEScct-LOG_to_LINEAR, inverse)",
            "acescct_to_ap0: ACEScct -> ACES2065-1 (ACEScct_to_ACES2065-1)",
            "ap0_to_acescc: ACES2065-1 -> ACEScc (ACEScc_to_ACES2065-1, inverse)",
            "acescc_to_ap0: ACEScc -> ACES2065-1 (ACEScc_to_ACES2065-1)",
        ],
        rows,
    )


def rgc13(rng, samples):
    # Default ACES 1.3 RGC parameters: limits (cyan, magenta, yellow),
    # thresholds (cyan, magenta, yellow), power.
    params = [1.147, 1.264, 1.312, 0.815, 0.803, 0.880, 1.2]
    # RGC works on ACEScg (AP1); feed AP0 samples converted by OCIO's own
    # matrix so the golden inputs are AP0 exactly like the other files.
    ap0 = samples + [
        # Strongly out-of-AP1 colours (the case RGC exists for).
        [1.0, -0.2, -0.1], [-0.1, 1.0, -0.3], [-0.2, -0.1, 1.0], [0.5, 0.5, -0.4], [2.0, -0.5, 1.5],
    ]
    rows = []
    t = ocio.FixedFunctionTransform(style=ocio.FIXED_FUNCTION_ACES_GAMUT_COMP_13, params=params)
    # OCIO applies the fixed function to AP1 data. Convert with the builtin
    # ACEScg (AP1) <-> ACES2065-1 matrix via a MatrixTransform of the exact
    # SMPTE values used by the CTL.
    ap0_to_ap1 = [
        1.4514393161, -0.2365107469, -0.2149285693, 0.0,
        -0.0765537734, 1.1762296998, -0.0996759264, 0.0,
        0.0083161484, -0.0060324498, 0.9977163014, 0.0,
        0.0, 0.0, 0.0, 1.0,
    ]
    m = ocio.MatrixTransform(matrix=ap0_to_ap1)
    ap1 = run(m, ap0)
    fwd = run(t, ap1)
    for a, b in zip(ap1, fwd):
        rows.append(["fwd"] + [fmt(v) for v in a] + [fmt(v) for v in b])
    back = run(t, fwd, inverse=True)
    for a, b in zip(fwd, back):
        rows.append(["inv"] + [fmt(v) for v in a] + [fmt(v) for v in b])
    write_csv(
        "aces_ocio_rgc13.csv",
        [
            "FIXED_FUNCTION_ACES_GAMUT_COMP_13 with the default parameters "
            "lim=(1.147,1.264,1.312) thr=(0.815,0.803,0.880) power=1.2",
            "columns: dir,in_r,in_g,in_b,out_r,out_g,out_b (ACEScg / AP1 linear)",
        ],
        rows,
    )


def cdl(rng, samples):
    configs = [
        ("warm", [1.1, 1.0, 0.9], [0.02, 0.0, -0.01], [0.95, 1.0, 1.05], 1.2),
        ("desat", [0.8, 0.9, 1.2], [-0.05, 0.03, 0.1], [1.3, 0.7, 1.0], 0.4),
        ("extreme", [2.0, 0.5, 1.5], [0.3, -0.2, 0.05], [0.5, 2.0, 1.0], 0.0),
    ]
    # CDL is meant for display-referred-ish / log data; include >1 and negatives.
    vals = samples[::4] + [[1.5, 0.2, -0.1], [-0.3, 2.0, 0.8], [0.9, 0.9, 1.1]]
    rows = []
    for name, slope, offset, power, sat in configs:
        for style_name, style in [("asc", ocio.CDL_ASC), ("noclamp", ocio.CDL_NO_CLAMP)]:
            t = ocio.CDLTransform(slope=slope, offset=offset, power=power, sat=sat)
            t.setStyle(style)
            out = run(t, vals)
            for a, b in zip(vals, out):
                rows.append([name, style_name, "fwd"] + [fmt(v) for v in a] + [fmt(v) for v in b])
            back = run(t, out, inverse=True)
            for a, b in zip(out, back):
                rows.append([name, style_name, "inv"] + [fmt(v) for v in a] + [fmt(v) for v in b])
    write_csv(
        "aces_ocio_cdl.csv",
        [
            "ASC CDL via OCIO CDLTransform, styles ASC (clamping) and NO_CLAMP",
            "columns: config,style,dir,in_r,in_g,in_b,out_r,out_g,out_b",
            "configs: " + "; ".join(f"{n}: slope={s} offset={o} power={p} sat={t}" for n, s, o, p, t in configs),
        ],
        rows,
    )


def main():
    rng = random.Random(20260828)
    samples = scene_samples(rng)
    display_encoding(rng, samples)
    acescct(rng)
    rgc13(rng, samples)
    cdl(rng, samples)


if __name__ == "__main__":
    main()
