#!/usr/bin/env python3
"""Generate ACES 2.0 Output Transform golden files from OpenColorIO.

OpenColorIO >= 2.4 ships the ACES 2.0 rendering as built-in fixed functions
that expose every stage of the CTL reference (`Lib.Academy.OutputTransform.ctl`
in https://github.com/aces-aswf/aces-core):

  FIXED_FUNCTION_ACES_RGB_TO_JMH_20         RGB (given primaries) -> Hellwig JMh
  FIXED_FUNCTION_ACES_TONESCALE_COMPRESS_20 JMh -> tonescaled + chroma-compressed JMh
  FIXED_FUNCTION_ACES_GAMUT_COMPRESS_20     JMh -> gamut-compressed JMh
  FIXED_FUNCTION_ACES_OUTPUT_TRANSFORM_20   AP0 RGB -> display-linear RGB (limiting primaries)

This script drives those through a raw config and writes one CSV per stage to
`golden/`. `tests/aces2_reference.rs` replays the inputs through zentone's port
and asserts parity.

Usage (needs `opencolorio` and `numpy`; e.g. `uv pip install opencolorio numpy`):

    python3 reference-checks/aces2_ocio_reference.py

The sample set is deterministic (fixed RNG seed), so re-running regenerates
byte-identical files for the same OCIO version.
"""

import os
import random

import numpy as np
import PyOpenColorIO as ocio

HERE = os.path.dirname(os.path.abspath(__file__))
GOLDEN = os.path.join(HERE, "golden")

# Chromaticities as OCIO wants them: rx ry gx gy bx by wx wy.
PRIMARIES = {
    "ap0": [0.73470, 0.26530, 0.00000, 1.00000, 0.00010, -0.07700, 0.32168, 0.33767],
    "ap1": [0.713, 0.293, 0.165, 0.830, 0.128, 0.044, 0.32168, 0.33767],
    "rec709": [0.640, 0.330, 0.300, 0.600, 0.150, 0.060, 0.3127, 0.3290],
    "p3d65": [0.680, 0.320, 0.265, 0.690, 0.150, 0.060, 0.3127, 0.3290],
    "rec2020": [0.708, 0.292, 0.170, 0.797, 0.131, 0.046, 0.3127, 0.3290],
}

CFG = ocio.Config.CreateRaw()


def apply(style, params, rows):
    t = ocio.FixedFunctionTransform(style=style, params=params)
    cpu = CFG.getProcessor(t).getDefaultCPUProcessor()
    a = np.array(rows, dtype=np.float32).reshape(-1, 3).copy()
    cpu.applyRGB(a)
    return a


def rgb_samples(rng):
    """A fixed, mixed bag of scene-linear RGB triples."""
    out = []
    for g in [0.0, 1e-4, 1e-3, 0.01, 0.05, 0.18, 0.5, 1.0, 2.0, 8.0, 32.0, 100.0]:
        out.append([g, g, g])
    corners = [[1, 0, 0], [1, 1, 0], [0, 1, 0], [0, 1, 1], [0, 0, 1], [1, 0, 1]]
    for scale in [0.05, 0.5, 1.0, 10.0]:
        for c in corners:
            out.append([scale * v for v in c])
    # Log-uniform random colours across 5 decades, moderately saturated.
    for _ in range(30):
        lum = 10 ** rng.uniform(-3, 2)
        r, g, b = (rng.uniform(0.05, 1.0) for _ in range(3))
        m = max(r, g, b)
        out.append([lum * r / m, lum * g / m, lum * b / m])
    # Slightly negative / out-of-gamut inputs (AP0 can encode these).
    for _ in range(8):
        out.append([rng.uniform(-0.05, 0.3), rng.uniform(-0.05, 0.3), rng.uniform(-0.05, 0.3)])
    return out


def fmt(v):
    # Shortest decimal that round-trips the f32 (numpy's str), not the f64 repr.
    return str(np.float32(v))


def write_csv(name, header_lines, rows):
    path = os.path.join(GOLDEN, name)
    with open(path, "w") as f:
        f.write(f"# generated by reference-checks/aces2_ocio_reference.py, OpenColorIO {ocio.__version__}\n")
        for h in header_lines:
            f.write(f"# {h}\n")
        for row in rows:
            f.write(",".join(row) + "\n")
    print(f"wrote {path} ({len(rows)} rows)")


def main():
    rng = random.Random(20260827)
    samples = rgb_samples(rng)

    # Stage 1: RGB -> JMh for several input primaries.
    rows = []
    jmh_by_prims = {}
    for name in ["ap0", "ap1", "rec709", "rec2020"]:
        out = apply(ocio.FIXED_FUNCTION_ACES_RGB_TO_JMH_20, PRIMARIES[name], samples)
        jmh_by_prims[name] = out
        for rgb, jmh in zip(samples, out):
            rows.append([name] + [fmt(v) for v in rgb] + [fmt(v) for v in jmh])
    write_csv(
        "aces2_ocio_jmh.csv",
        ["FIXED_FUNCTION_ACES_RGB_TO_JMH_20", "columns: primaries,r,g,b,J,M,h"],
        rows,
    )

    # Stage 2: tonescale + chroma compression on AP0 JMh, per peak luminance.
    rows = []
    ts_by_peak = {}
    jmh_ap0 = jmh_by_prims["ap0"]
    for peak in [100.0, 1000.0, 4000.0]:
        out = apply(ocio.FIXED_FUNCTION_ACES_TONESCALE_COMPRESS_20, [peak], jmh_ap0)
        ts_by_peak[peak] = out
        for a, b in zip(jmh_ap0, out):
            rows.append([fmt(peak)] + [fmt(v) for v in a] + [fmt(v) for v in b])
    write_csv(
        "aces2_ocio_tonescale_compress.csv",
        ["FIXED_FUNCTION_ACES_TONESCALE_COMPRESS_20", "columns: peak_nits,J,M,h,J_out,M_out,h_out"],
        rows,
    )

    # Stage 3: gamut compression of the tonescaled JMh, per (peak, limiting primaries).
    rows = []
    for peak, prims in [(100.0, "rec709"), (100.0, "p3d65"), (1000.0, "rec2020")]:
        src = ts_by_peak[peak]
        out = apply(ocio.FIXED_FUNCTION_ACES_GAMUT_COMPRESS_20, [peak] + PRIMARIES[prims], src)
        for a, b in zip(src, out):
            rows.append([fmt(peak), prims] + [fmt(v) for v in a] + [fmt(v) for v in b])
    write_csv(
        "aces2_ocio_gamut_compress.csv",
        ["FIXED_FUNCTION_ACES_GAMUT_COMPRESS_20", "columns: peak_nits,limiting_primaries,J,M,h,J_out,M_out,h_out"],
        rows,
    )

    # Stage 4: the whole output transform, AP0 RGB -> display-linear RGB.
    rows = []
    for peak, prims in [(100.0, "rec709"), (100.0, "p3d65"), (1000.0, "rec2020"), (4000.0, "rec2020")]:
        out = apply(ocio.FIXED_FUNCTION_ACES_OUTPUT_TRANSFORM_20, [peak] + PRIMARIES[prims], samples)
        for rgb, o in zip(samples, out):
            rows.append([fmt(peak), prims] + [fmt(v) for v in rgb] + [fmt(v) for v in o])
    inv_rows = []
    for peak, prims in [(100.0, "rec709"), (100.0, "p3d65"), (1000.0, "rec2020"), (4000.0, "rec2020")]:
        params = [peak] + PRIMARIES[prims]
        fwd = apply(ocio.FIXED_FUNCTION_ACES_OUTPUT_TRANSFORM_20, params, samples)
        t = ocio.FixedFunctionTransform(style=ocio.FIXED_FUNCTION_ACES_OUTPUT_TRANSFORM_20, params=params)
        t.setDirection(ocio.TRANSFORM_DIR_INVERSE)
        cpu = CFG.getProcessor(t).getDefaultCPUProcessor()
        back = np.array(fwd, dtype=np.float32).copy()
        cpu.applyRGB(back)
        for d, a in zip(fwd, back):
            inv_rows.append([fmt(peak), prims] + [fmt(v) for v in d] + [fmt(v) for v in a])
    write_csv(
        "aces2_ocio_output_transform_inv.csv",
        [
            "FIXED_FUNCTION_ACES_OUTPUT_TRANSFORM_20 (inverse direction)",
            "columns: peak_nits,limiting_primaries,r_display,g_display,b_display,r_ap0,g_ap0,b_ap0",
            "inputs are the forward outputs of aces2_ocio_output_transform.csv",
        ],
        inv_rows,
    )
    write_csv(
        "aces2_ocio_output_transform.csv",
        [
            "FIXED_FUNCTION_ACES_OUTPUT_TRANSFORM_20",
            "columns: peak_nits,limiting_primaries,r,g,b,r_out,g_out,b_out",
            "output is display-linear in the limiting primaries, 1.0 = 100 cd/m^2",
        ],
        rows,
    )


if __name__ == "__main__":
    main()
