// libultrahdr_reinhard.cpp
//
// Standalone extraction of libultrahdr's ReinhardMap / globalTonemap
// functions for comparison against zentone's `reinhard_extended` helper.
//
// Source file : lib/src/jpegr.cpp (lines 1817-1849)
// Upstream    : https://github.com/google/libultrahdr
// Commit      : 8cbc983 (HEAD of ~/work/libultrahdr as of 2026-04-11)
// License     : Apache-2.0
// Permalink   : https://github.com/google/libultrahdr/blob/main/lib/src/jpegr.cpp
//
// The formula is:
//     ReinhardMap(y, h) = y * (1 + y/h^2) / (1 + y)
// Extended Reinhard where `h` is the HDR headroom in units of SDR white
// (e.g. h = 4.0 for content peak at 4× SDR white).
//
// For globalTonemap: scale rgb_in by headroom, take the channel max, pass
// through ReinhardMap with the same headroom, and scale all three channels
// by max_sdr / max_hdr. Alpha/chroma is untouched.

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdio>

// ---------- verbatim from libultrahdr lib/src/jpegr.cpp:1817-1849 ----------

static float ReinhardMap(float y_hdr, float headroom) {
    float out = 1.0f + y_hdr / (headroom * headroom);
    out /= 1.0f + y_hdr;
    return out * y_hdr;
}

struct GlobalTonemapOutputs {
    std::array<float, 3> rgb_out;
    float y_hdr;
    float y_sdr;
};

static GlobalTonemapOutputs globalTonemap(const std::array<float, 3>& rgb_in,
                                          float headroom, bool is_normalized) {
    std::array<float, 3> rgb_hdr;
    std::transform(rgb_in.begin(), rgb_in.end(), rgb_hdr.begin(),
                   [&](float x) { return is_normalized ? x * headroom : x; });

    float max_hdr = *std::max_element(rgb_hdr.begin(), rgb_hdr.end());
    float max_sdr = ReinhardMap(max_hdr, headroom);
    std::array<float, 3> rgb_sdr;
    std::transform(rgb_hdr.begin(), rgb_hdr.end(), rgb_sdr.begin(), [&](float x) {
        if (x > 0.0f) {
            return x * max_sdr / max_hdr;
        }
        return 0.0f;
    });

    GlobalTonemapOutputs out;
    out.rgb_out = rgb_sdr;
    out.y_hdr = max_hdr;
    out.y_sdr = max_sdr;
    return out;
}

// --------------------------------- harness ---------------------------------

// Test vectors: (headroom, y) for ReinhardMap scalar sweep.
// Headrooms cover typical UltraHDR ranges (2×, 4×, 8×, 16×).
// Scalar values cover shadows (0.01), mid-gray (0.18), white (1.0), and
// bright HDR highlights up to the headroom limit.
int main() {
    std::puts("# libultrahdr ReinhardMap golden vectors");
    std::puts("# columns: headroom, y_hdr, y_sdr");
    std::puts("# format: %.9g (decimal), generated by libultrahdr_reinhard.cpp");
    std::puts("# reference: lib/src/jpegr.cpp:1817 @ libultrahdr commit 8cbc983");
    std::puts("headroom,y_hdr,y_sdr");

    const float headrooms[] = {2.0f, 4.0f, 8.0f, 16.0f};
    const float ys[] = {
        0.0f,    0.001f,  0.01f,    0.05f,   0.1f, 0.18f, 0.25f,
        0.5f,    0.75f,   1.0f,     1.5f,    2.0f, 2.5f,  3.0f,
        3.5f,    4.0f,    6.0f,     8.0f,    12.0f, 16.0f, 32.0f,
    };

    for (float h : headrooms) {
        for (float y : ys) {
            float out = ReinhardMap(y, h);
            std::printf("%.9g,%.9g,%.9g\n", (double)h, (double)y, (double)out);
        }
    }

    // globalTonemap vectors: apply extended Reinhard to RGB triples and
    // verify the channel-max + ratio scaling.
    std::puts("");
    std::puts("# globalTonemap vectors");
    std::puts("# columns: headroom, r_in, g_in, b_in, r_out, g_out, b_out");
    std::puts("headroom,r_in,g_in,b_in,r_out,g_out,b_out");

    const std::array<std::array<float, 3>, 6> rgbs = {{
        {0.0f, 0.0f, 0.0f},
        {0.5f, 0.5f, 0.5f},
        {1.0f, 0.5f, 0.25f},
        {0.2f, 0.9f, 0.1f},
        {0.95f, 0.1f, 0.05f},
        {0.8f, 0.8f, 0.2f},
    }};

    for (float h : headrooms) {
        for (const auto& rgb : rgbs) {
            auto out = globalTonemap(rgb, h, /*is_normalized=*/true);
            std::printf("%.9g,%.9g,%.9g,%.9g,%.9g,%.9g,%.9g\n",
                        (double)h,
                        (double)rgb[0], (double)rgb[1], (double)rgb[2],
                        (double)out.rgb_out[0], (double)out.rgb_out[1], (double)out.rgb_out[2]);
        }
    }

    return 0;
}
