//! ACES colour encodings and the small scene-referred operators that
//! surround the ACES 2.0 Output Transform: ACEScct / ACEScc log encodings,
//! the ASC CDL, and the ACES 1.3 Reference Gamut Compression.
//!
//! All of these operate on **AP1 (ACEScg) linear** data unless stated
//! otherwise; [`ap0_to_ap1`] / [`ap1_to_ap0`] convert to and from
//! ACES2065-1 with the SMPTE ST 2065-1 matrices the Academy CTL uses.
//!
//! Sources (verbatim formulas, no reinterpretation):
//!
//! - ACEScct: Academy S-2016-001 (`ACEScsc.Academy.ACEScct_to_ACES.ctl`).
//! - ACEScc: Academy S-2014-003 (`ACEScsc.Academy.ACEScc_to_ACES.ctl`).
//! - ASC CDL v1.2 (slope / offset / power / saturation with Rec.709 luma).
//! - Reference Gamut Compression: ACES 1.3
//!   `LMT.Academy.ReferenceGamutCompress.ctl`
//!   (<https://docs.acescentral.com/rgc/specification/>).
//!
//! **Parity.** Held to OpenColorIO 2.5's builtins on
//! `reference-checks/golden/aces_ocio_{acescct,rgc13,cdl}.csv`
//! (generated by `reference-checks/aces_ocio_encodings_reference.py`).

use libm::{exp2f, log2f, powf};

/// Largest finite half-float, the ceiling of both log encodings.
const HALF_MAX: f32 = 65504.0;
/// `log2(65504)`.
const LOG2_HALF_MAX: f32 = 15.999_129_6;

// -- ACES2065-1 <-> ACEScg ----------------------------------------------------

/// AP0 → AP1 (`AP0_2_AP1_MAT` in the Academy CTL, row-vector convention).
const AP0_TO_AP1: [[f32; 3]; 3] = [
    [1.451_439_316_1, -0.076_553_773_4, 0.008_316_148_4],
    [-0.236_510_746_9, 1.176_229_699_8, -0.006_032_449_8],
    [-0.214_928_569_3, -0.099_675_926_4, 0.997_716_301_4],
];

/// AP1 → AP0 (`AP1_2_AP0_MAT`).
const AP1_TO_AP0: [[f32; 3]; 3] = [
    [0.695_452_241_4, 0.044_794_563_2, -0.005_525_882_6],
    [0.140_678_696_5, 0.859_671_118_9, 0.004_025_210_0],
    [0.163_869_062_1, 0.095_534_317_9, 1.001_500_672_6],
];

#[inline]
fn mul_vm(v: [f32; 3], m: &[[f32; 3]; 3]) -> [f32; 3] {
    [
        v[0] * m[0][0] + v[1] * m[1][0] + v[2] * m[2][0],
        v[0] * m[0][1] + v[1] * m[1][1] + v[2] * m[2][1],
        v[0] * m[0][2] + v[1] * m[1][2] + v[2] * m[2][2],
    ]
}

/// ACES2065-1 (AP0) linear → ACEScg (AP1) linear.
#[must_use]
#[inline]
pub fn ap0_to_ap1(aces: [f32; 3]) -> [f32; 3] {
    mul_vm(aces, &AP0_TO_AP1)
}

/// ACEScg (AP1) linear → ACES2065-1 (AP0) linear.
#[must_use]
#[inline]
pub fn ap1_to_ap0(acescg: [f32; 3]) -> [f32; 3] {
    mul_vm(acescg, &AP1_TO_AP0)
}

// -- ACEScct ------------------------------------------------------------------

const ACESCCT_CUT_LIN: f32 = 0.007_812_5;
const ACESCCT_CUT_LOG: f32 = 0.155_251_141_552_511;
const ACESCCT_A: f32 = 10.540_237_741_654_5;
const ACESCCT_B: f32 = 0.072_905_534_195_835_5;

/// ACEScct encode: AP1 linear → ACEScct (S-2016-001). Linear below
/// `0.0078125` (so negatives encode linearly), `(log2 x + 9.72) / 17.52` above.
#[must_use]
#[inline]
pub fn acescct_encode(lin: f32) -> f32 {
    if lin <= ACESCCT_CUT_LIN {
        ACESCCT_A * lin + ACESCCT_B
    } else {
        (log2f(lin) + 9.72) / 17.52
    }
}

/// ACEScct decode: ACEScct → AP1 linear. Clamps to `65504` at the top.
#[must_use]
#[inline]
pub fn acescct_decode(cct: f32) -> f32 {
    if cct <= ACESCCT_CUT_LOG {
        (cct - ACESCCT_B) / ACESCCT_A
    } else if cct < (LOG2_HALF_MAX + 9.72) / 17.52 {
        exp2f(cct * 17.52 - 9.72)
    } else {
        HALF_MAX
    }
}

// -- ACEScc -------------------------------------------------------------------

/// ACEScc encode: AP1 linear → ACEScc (S-2014-003). Non-positive input
/// encodes as `2⁻¹⁶`; a lifted `2⁻¹⁶ + x/2` segment below `2⁻¹⁵`.
#[must_use]
#[inline]
pub fn acescc_encode(lin: f32) -> f32 {
    const TWO_POW_M16: f32 = 1.525_878_906_25e-5;
    const TWO_POW_M15: f32 = 3.051_757_812_5e-5;
    if lin <= 0.0 {
        (-16.0 + 9.72) / 17.52
    } else if lin < TWO_POW_M15 {
        (log2f(TWO_POW_M16 + lin * 0.5) + 9.72) / 17.52
    } else {
        (log2f(lin) + 9.72) / 17.52
    }
}

/// ACEScc decode: ACEScc → AP1 linear. Clamps to `65504` at the top.
#[must_use]
#[inline]
pub fn acescc_decode(cc: f32) -> f32 {
    const TWO_POW_M16: f32 = 1.525_878_906_25e-5;
    if cc < (9.72 - 15.0) / 17.52 {
        (exp2f(cc * 17.52 - 9.72) - TWO_POW_M16) * 2.0
    } else if cc < (LOG2_HALF_MAX + 9.72) / 17.52 {
        exp2f(cc * 17.52 - 9.72)
    } else {
        HALF_MAX
    }
}

/// Apply a scalar encoding to every element of a buffer (any channel
/// layout — alpha included, so pass RGB-only data or split alpha first).
#[inline]
pub fn apply_scalar(buf: &mut [f32], f: impl Fn(f32) -> f32) {
    for v in buf.iter_mut() {
        *v = f(*v);
    }
}

// -- ASC CDL ------------------------------------------------------------------

/// ASC CDL v1.2 colour decision list: per-channel slope / offset / power
/// and a saturation blend around Rec.709 luma.
///
/// `out = sat_blend(clamp((in × slope + offset)) ^ power)` — the "ASC"
/// style clamps to `[0, 1]` after slope/offset and after saturation; the
/// no-clamp style ([`apply_no_clamp`](Self::apply_no_clamp)) leaves the
/// range open and applies `power` only to non-negative values.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AscCdl {
    /// Per-channel gain, applied first. Identity `1.0`.
    pub slope: [f32; 3],
    /// Per-channel lift, added after `slope`. Identity `0.0`.
    pub offset: [f32; 3],
    /// Per-channel gamma. Identity `1.0`.
    pub power: [f32; 3],
    /// Saturation about Rec.709 luma. Identity `1.0`; `0.0` is greyscale.
    pub saturation: f32,
}

/// Rec.709 luma weights the CDL specification prescribes.
const CDL_LUMA: [f32; 3] = [0.2126, 0.7152, 0.0722];

impl AscCdl {
    /// The identity CDL.
    pub const IDENTITY: Self = Self {
        slope: [1.0; 3],
        offset: [0.0; 3],
        power: [1.0; 3],
        saturation: 1.0,
    };

    /// True when every parameter is finite and the CDL is invertible
    /// (`slope` and `power` non-zero, `saturation` non-zero).
    #[must_use]
    pub fn is_invertible(&self) -> bool {
        self.slope.iter().all(|s| s.is_finite() && *s != 0.0)
            && self.offset.iter().all(|o| o.is_finite())
            && self.power.iter().all(|p| p.is_finite() && *p != 0.0)
            && self.saturation.is_finite()
            && self.saturation != 0.0
    }

    #[inline]
    fn sop_clamped(&self, rgb: [f32; 3]) -> [f32; 3] {
        let mut out = [0.0f32; 3];
        for c in 0..3 {
            let v = (rgb[c] * self.slope[c] + self.offset[c]).clamp(0.0, 1.0);
            out[c] = powf(v, self.power[c]);
        }
        out
    }

    #[inline]
    fn sop_open(&self, rgb: [f32; 3]) -> [f32; 3] {
        let mut out = [0.0f32; 3];
        for c in 0..3 {
            let v = rgb[c] * self.slope[c] + self.offset[c];
            out[c] = if v >= 0.0 { powf(v, self.power[c]) } else { v };
        }
        out
    }

    #[inline]
    fn saturate(&self, rgb: [f32; 3]) -> [f32; 3] {
        let luma = rgb[0] * CDL_LUMA[0] + rgb[1] * CDL_LUMA[1] + rgb[2] * CDL_LUMA[2];
        [
            luma + self.saturation * (rgb[0] - luma),
            luma + self.saturation * (rgb[1] - luma),
            luma + self.saturation * (rgb[2] - luma),
        ]
    }

    #[inline]
    fn desaturate(&self, rgb: [f32; 3]) -> [f32; 3] {
        let luma = rgb[0] * CDL_LUMA[0] + rgb[1] * CDL_LUMA[1] + rgb[2] * CDL_LUMA[2];
        let inv = 1.0 / self.saturation;
        [
            luma + inv * (rgb[0] - luma),
            luma + inv * (rgb[1] - luma),
            luma + inv * (rgb[2] - luma),
        ]
    }

    /// Forward CDL, "ASC" style: clamp to `[0, 1]` after slope/offset and
    /// after saturation.
    #[must_use]
    pub fn apply(&self, rgb: [f32; 3]) -> [f32; 3] {
        let s = self.saturate(self.sop_clamped(rgb));
        [
            s[0].clamp(0.0, 1.0),
            s[1].clamp(0.0, 1.0),
            s[2].clamp(0.0, 1.0),
        ]
    }

    /// Forward CDL without clamping (for log or scene-linear data).
    /// `power` is applied to non-negative values only; negatives pass
    /// through slope/offset and saturation unchanged.
    #[must_use]
    pub fn apply_no_clamp(&self, rgb: [f32; 3]) -> [f32; 3] {
        self.saturate(self.sop_open(rgb))
    }

    /// Inverse of [`apply`](Self::apply) (with the same clamps, so only
    /// exact for values the forward did not clip). Requires
    /// [`is_invertible`](Self::is_invertible).
    #[must_use]
    pub fn inverse(&self, rgb: [f32; 3]) -> [f32; 3] {
        let d = self.desaturate([
            rgb[0].clamp(0.0, 1.0),
            rgb[1].clamp(0.0, 1.0),
            rgb[2].clamp(0.0, 1.0),
        ]);
        let mut out = [0.0f32; 3];
        for c in 0..3 {
            let v = powf(d[c].clamp(0.0, 1.0), 1.0 / self.power[c]);
            out[c] = ((v - self.offset[c]) / self.slope[c]).clamp(0.0, 1.0);
        }
        out
    }

    /// Inverse of [`apply_no_clamp`](Self::apply_no_clamp). Requires
    /// [`is_invertible`](Self::is_invertible).
    #[must_use]
    pub fn inverse_no_clamp(&self, rgb: [f32; 3]) -> [f32; 3] {
        let d = self.desaturate(rgb);
        let mut out = [0.0f32; 3];
        for c in 0..3 {
            let v = if d[c] >= 0.0 {
                powf(d[c], 1.0 / self.power[c])
            } else {
                d[c]
            };
            out[c] = (v - self.offset[c]) / self.slope[c];
        }
        out
    }
}

impl Default for AscCdl {
    fn default() -> Self {
        Self::IDENTITY
    }
}

// -- ACES 1.3 Reference Gamut Compression ---------------------------------------

/// ACES 1.3 Reference Gamut Compression (`LMT.Academy.ReferenceGamutCompress`):
/// pulls colours outside AP1 back inside by compressing each channel's
/// distance from the achromatic axis, in ACEScg.
///
/// Per channel `c` with `ach = max(r, g, b)` and distance
/// `d = (ach − c) / |ach|`, distances above `threshold` are compressed
/// towards `1.0` by `d' = t + s·(d−t)/s / (1 + ((d−t)/s)^p)^(1/p)` so that a
/// distance of `limit` lands on the AP1 boundary (`1.0`). The three
/// thresholds/limits are for the cyan, magenta, yellow directions, i.e.
/// the R, G, B channels' distances.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ReferenceGamutCompression {
    /// Distance below which a channel is untouched, per (R, G, B).
    pub threshold: [f32; 3],
    /// Distance mapped onto the gamut boundary, per (R, G, B). Must exceed
    /// the threshold, and exceed `1.0` for the compression to reach outside AP1.
    pub limit: [f32; 3],
    /// Curve exponent (`1.2` in the spec).
    pub power: f32,
}

impl ReferenceGamutCompression {
    /// The ACES 1.3 parameters: `threshold = (0.815, 0.803, 0.880)`,
    /// `limit = (1.147, 1.264, 1.312)`, `power = 1.2`.
    pub const ACES_1_3: Self = Self {
        threshold: [0.815, 0.803, 0.880],
        limit: [1.147, 1.264, 1.312],
        power: 1.2,
    };

    /// True when the parameters define a valid, invertible compression:
    /// `0 ≤ threshold < 1 < limit` per channel and a finite `power > 0`.
    #[must_use]
    pub fn is_valid(&self) -> bool {
        (0..3).all(|c| {
            self.threshold[c].is_finite()
                && self.limit[c].is_finite()
                && self.threshold[c] >= 0.0
                && self.threshold[c] < 1.0
                && self.limit[c] > 1.0
        }) && self.power.is_finite()
            && self.power > 0.0
    }

    /// `compress` in the CTL: one distance, forward or inverse.
    fn compress(dist: f32, lim: f32, thr: f32, pwr: f32, invert: bool) -> f32 {
        if dist < thr {
            return dist;
        }
        // Scale so that `lim` maps to exactly 1.0.
        let s = (lim - thr) / powf(powf((1.0 - thr) / (lim - thr), -pwr) - 1.0, 1.0 / pwr);
        let nd = (dist - thr) / s;
        if !invert {
            let p = powf(nd, pwr);
            thr + s * nd / powf(1.0 + p, 1.0 / pwr)
        } else {
            if dist > thr + s {
                return dist;
            }
            let p = powf(nd, pwr);
            thr + s * powf(-(p / (p - 1.0)), 1.0 / pwr)
        }
    }

    fn run(&self, rgb: [f32; 3], invert: bool) -> [f32; 3] {
        let ach = rgb[0].max(rgb[1]).max(rgb[2]);
        if ach == 0.0 {
            return rgb;
        }
        let abs_ach = ach.abs();
        let mut out = [0.0f32; 3];
        for c in 0..3 {
            let d = (ach - rgb[c]) / abs_ach;
            let cd = Self::compress(d, self.limit[c], self.threshold[c], self.power, invert);
            out[c] = ach - cd * abs_ach;
        }
        out
    }

    /// Forward compression on an ACEScg (AP1) linear triple.
    #[must_use]
    pub fn apply(&self, acescg: [f32; 3]) -> [f32; 3] {
        self.run(acescg, false)
    }

    /// Inverse compression (exact for distances the forward mapped from
    /// below `threshold + s`; beyond that the forward is not injective and
    /// the value passes through, as in the CTL).
    #[must_use]
    pub fn inverse(&self, acescg: [f32; 3]) -> [f32; 3] {
        self.run(acescg, true)
    }

    /// Forward compression over interleaved RGB / RGBA rows in place.
    /// `channels` must be 3 or 4 (alpha is left untouched); a row whose
    /// length is not a multiple of `channels` has its tail ignored.
    pub fn apply_row(&self, row: &mut [f32], channels: usize) {
        match channels {
            3 => self.row_cn::<3>(row, false),
            4 => self.row_cn::<4>(row, false),
            _ => {}
        }
    }

    /// Inverse compression over interleaved rows; see [`apply_row`](Self::apply_row).
    pub fn inverse_row(&self, row: &mut [f32], channels: usize) {
        match channels {
            3 => self.row_cn::<3>(row, true),
            4 => self.row_cn::<4>(row, true),
            _ => {}
        }
    }

    fn row_cn<const CN: usize>(&self, row: &mut [f32], invert: bool) {
        for px in row.chunks_exact_mut(CN) {
            let out = self.run([px[0], px[1], px[2]], invert);
            px[0] = out[0];
            px[1] = out[1];
            px[2] = out[2];
        }
    }
}

impl Default for ReferenceGamutCompression {
    fn default() -> Self {
        Self::ACES_1_3
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec::Vec;

    const ACESCCT_CSV: &str = include_str!("../../reference-checks/golden/aces_ocio_acescct.csv");
    const RGC_CSV: &str = include_str!("../../reference-checks/golden/aces_ocio_rgc13.csv");
    const CDL_CSV: &str = include_str!("../../reference-checks/golden/aces_ocio_cdl.csv");

    fn rows(csv: &str) -> Vec<Vec<&str>> {
        csv.lines()
            .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
            .map(|l| l.split(',').collect())
            .collect()
    }

    fn f(s: &str) -> f32 {
        s.trim()
            .parse()
            .unwrap_or_else(|_| panic!("bad float {s:?}"))
    }

    fn close(got: f32, want: f32, abs: f32, rel: f32) -> bool {
        (got - want).abs() <= abs + want.abs() * rel
    }

    #[test]
    fn acescct_and_acescc_match_ocio() {
        let mut counts = [0usize; 4];
        for r in rows(ACESCCT_CSV) {
            let inp = [f(r[1]), f(r[2]), f(r[3])];
            let want = [f(r[4]), f(r[5]), f(r[6])];
            let (got, k): ([f32; 3], usize) = match r[0] {
                "acescct" => (inp.map(acescct_encode), 0),
                "acescct_to_ap0" => (ap1_to_ap0(inp.map(acescct_decode)), 1),
                "ap0_to_acescc" => (ap0_to_ap1(inp).map(acescc_encode), 2),
                "acescc_to_ap0" => (ap1_to_ap0(inp.map(acescc_decode)), 3),
                other => panic!("unknown kind {other}"),
            };
            counts[k] += 1;
            for c in 0..3 {
                // Log values: 1e-5 absolute. Linear: 1e-5 relative (the
                // matrix + exp2 chain) with a 1e-6 floor.
                assert!(
                    close(got[c], want[c], 2e-5, 2e-5),
                    "{} {inp:?}: {got:?} vs {want:?}",
                    r[0]
                );
            }
        }
        assert!(counts.iter().all(|&n| n >= 50), "{counts:?}");
    }

    #[test]
    fn log_encodings_round_trip_and_anchor() {
        // 18% grey encodes to 0.4135884 in both (the log segment).
        assert!((acescct_encode(0.18) - 0.413_588_4).abs() < 1e-6);
        assert!((acescc_encode(0.18) - 0.413_588_4).abs() < 1e-6);
        // The ACEScct toe joins the log segment continuously.
        let a = acescct_encode(ACESCCT_CUT_LIN);
        let b = acescct_encode(ACESCCT_CUT_LIN * 1.000_01);
        assert!((a - b).abs() < 1e-5, "{a} vs {b}");
        assert!((a - ACESCCT_CUT_LOG).abs() < 1e-6, "{a}");
        for i in 0..=400 {
            let lin = exp2f(i as f32 / 400.0 * 36.0 - 20.0); // 2^-20 .. 2^16
            let lin = lin.min(HALF_MAX);
            assert!(
                close(acescct_decode(acescct_encode(lin)), lin, 1e-9, 1e-5),
                "cct {lin}"
            );
            assert!(
                close(acescc_decode(acescc_encode(lin)), lin, 1e-9, 1e-5),
                "cc {lin}"
            );
        }
        // ACEScct is linear (and invertible) below zero; ACEScc pins.
        assert!(close(
            acescct_decode(acescct_encode(-0.25)),
            -0.25,
            1e-7,
            1e-6
        ));
        assert_eq!(acescc_encode(-1.0), acescc_encode(0.0));
        // Both clamp to half-max at the top (the log segment reaches it at
        // code value ~1.468).
        assert_eq!(acescct_decode(1.5), HALF_MAX);
        assert_eq!(acescc_decode(1.5), HALF_MAX);
        assert!(acescct_decode(1.0) < HALF_MAX);
        // The AP0/AP1 matrices are mutual inverses.
        let v = ap1_to_ap0(ap0_to_ap1([0.3, 0.6, 0.1]));
        assert!(
            close(v[0], 0.3, 1e-6, 0.0)
                && close(v[1], 0.6, 1e-6, 0.0)
                && close(v[2], 0.1, 1e-6, 0.0),
            "{v:?}"
        );
        // Buffer helper touches every element.
        let mut buf = [0.18f32; 7];
        apply_scalar(&mut buf, acescct_encode);
        assert!(buf.iter().all(|&v| (v - 0.413_588_4).abs() < 1e-6));
    }

    #[test]
    fn rgc13_matches_ocio() {
        let rgc = ReferenceGamutCompression::ACES_1_3;
        assert!(rgc.is_valid());
        let mut n = [0usize; 2];
        for r in rows(RGC_CSV) {
            let inp = [f(r[1]), f(r[2]), f(r[3])];
            let want = [f(r[4]), f(r[5]), f(r[6])];
            let (got, k) = match r[0] {
                "fwd" => (rgc.apply(inp), 0),
                "inv" => (rgc.inverse(inp), 1),
                other => panic!("{other}"),
            };
            n[k] += 1;
            for c in 0..3 {
                assert!(
                    close(got[c], want[c], 1e-5, 2e-5),
                    "{} {inp:?}: {got:?} vs {want:?}",
                    r[0]
                );
            }
        }
        assert!(n[0] >= 70 && n[1] >= 70, "{n:?}");
    }

    #[test]
    fn rgc_properties() {
        let rgc = ReferenceGamutCompression::default();
        // Inside the thresholds nothing moves; neutrals never move.
        assert_eq!(rgc.apply([0.5, 0.5, 0.5]), [0.5, 0.5, 0.5]);
        assert_eq!(rgc.apply([0.0; 3]), [0.0; 3]);
        let mild = [0.5, 0.3, 0.2];
        let out = rgc.apply(mild);
        assert!((0..3).all(|c| (out[c] - mild[c]).abs() <= 1e-7), "{out:?}");
        // A colour at exactly the limit distance lands on the AP1 boundary
        // (channel = 0), and one beyond it stays inside AP1.
        let at_limit = [1.0, 1.0 - 1.264, 1.0 - 1.312];
        let out = rgc.apply(at_limit);
        assert!(out[1].abs() < 1e-5 && out[2].abs() < 1e-5, "{out:?}");
        // Beyond the limit the curve keeps compressing towards its
        // asymptote `threshold + s` (≈ 1.09 for green: the spec's limit is
        // the largest distance the source encodings produce, not a hard
        // wall), so wildly out-of-gamut input lands just outside AP1.
        let beyond = [1.0, -0.8, -0.9];
        let out = rgc.apply(beyond);
        assert!(out.iter().all(|&c| c >= -0.1), "{out:?}");
        assert!(out[1] > beyond[1] && out[2] > beyond[2], "{out:?}");
        assert!(out[1] < 0.0 && out[2] < 0.0, "{out:?}");
        // Row form == per-pixel form, alpha untouched.
        let px = [[1.0, -0.2, -0.1], [0.4, 0.9, -0.3]];
        let mut row = [1.0, -0.2, -0.1, 0.7, 0.4, 0.9, -0.3, 0.2];
        rgc.apply_row(&mut row, 4);
        for (i, p) in px.iter().enumerate() {
            let want = rgc.apply(*p);
            for c in 0..3 {
                assert_eq!(row[i * 4 + c], want[c]);
            }
        }
        assert_eq!(row[3], 0.7);
        assert_eq!(row[7], 0.2);
        let mut back = row;
        rgc.inverse_row(&mut back, 4);
        for i in 0..2 {
            for c in 0..3 {
                assert!(close(back[i * 4 + c], px[i][c], 1e-5, 1e-5), "{back:?}");
            }
        }
        // Validation.
        assert!(!ReferenceGamutCompression { power: 0.0, ..rgc }.is_valid());
        assert!(
            !ReferenceGamutCompression {
                limit: [0.9, 1.2, 1.3],
                ..rgc
            }
            .is_valid()
        );
    }

    #[test]
    fn cdl_matches_ocio() {
        fn cfg(name: &str) -> AscCdl {
            match name {
                "warm" => AscCdl {
                    slope: [1.1, 1.0, 0.9],
                    offset: [0.02, 0.0, -0.01],
                    power: [0.95, 1.0, 1.05],
                    saturation: 1.2,
                },
                "desat" => AscCdl {
                    slope: [0.8, 0.9, 1.2],
                    offset: [-0.05, 0.03, 0.1],
                    power: [1.3, 0.7, 1.0],
                    saturation: 0.4,
                },
                "extreme" => AscCdl {
                    slope: [2.0, 0.5, 1.5],
                    offset: [0.3, -0.2, 0.05],
                    power: [0.5, 2.0, 1.0],
                    saturation: 0.0,
                },
                other => panic!("{other}"),
            }
        }
        let mut n = 0;
        for r in rows(CDL_CSV) {
            let cdl = cfg(r[0]);
            let inp = [f(r[3]), f(r[4]), f(r[5])];
            let want = [f(r[6]), f(r[7]), f(r[8])];
            let got = match (r[1], r[2]) {
                ("asc", "fwd") => cdl.apply(inp),
                ("noclamp", "fwd") => cdl.apply_no_clamp(inp),
                ("asc", "inv") => {
                    if !cdl.is_invertible() {
                        continue;
                    }
                    cdl.inverse(inp)
                }
                ("noclamp", "inv") => {
                    if !cdl.is_invertible() {
                        continue;
                    }
                    cdl.inverse_no_clamp(inp)
                }
                other => panic!("{other:?}"),
            };
            if want.iter().any(|v| !v.is_finite()) {
                continue;
            }
            n += 1;
            for c in 0..3 {
                assert!(
                    close(got[c], want[c], 2e-5, 2e-5),
                    "{} {} {} {inp:?}: {got:?} vs {want:?}",
                    r[0],
                    r[1],
                    r[2]
                );
            }
        }
        assert!(n >= 200, "only {n} rows compared");
    }

    #[test]
    fn cdl_identity_and_inverse() {
        let id = AscCdl::default();
        assert!(id.is_invertible());
        for v in [[0.0; 3], [0.18, 0.5, 0.9], [1.0; 3]] {
            assert_eq!(id.apply(v), v);
            assert_eq!(id.apply_no_clamp(v), v);
        }
        let warm = AscCdl {
            slope: [1.1, 1.0, 0.9],
            offset: [0.02, 0.0, -0.01],
            power: [0.95, 1.0, 1.05],
            saturation: 1.2,
        };
        for v in [[0.1, 0.2, 0.3], [0.5, 0.5, 0.5], [0.7, 0.2, 0.4]] {
            let back = warm.inverse(warm.apply(v));
            for c in 0..3 {
                assert!(close(back[c], v[c], 1e-5, 1e-5), "{v:?} -> {back:?}");
            }
            let open = warm.inverse_no_clamp(warm.apply_no_clamp([v[0] * 3.0, -v[1], v[2]]));
            let want = [v[0] * 3.0, -v[1], v[2]];
            for c in 0..3 {
                assert!(close(open[c], want[c], 1e-5, 1e-5), "{want:?} -> {open:?}");
            }
        }
        assert!(
            !AscCdl {
                saturation: 0.0,
                ..warm
            }
            .is_invertible()
        );
        assert!(
            !AscCdl {
                slope: [0.0, 1.0, 1.0],
                ..warm
            }
            .is_invertible()
        );
    }
}
