//! ACES 2.0 Output Transform — Hellwig 2022 JMh tonescale, chroma
//! compression, and gamut compression.
//!
//! A port of the ACES 2.0 rendering from the Academy's reference CTL
//! (`Lib.Academy.OutputTransform.ctl` / `Lib.Academy.Tonescale.ctl`,
//! <https://github.com/aces-aswf/aces-core>, `main` as of 2025-10). The
//! pipeline is:
//!
//! ```text
//! ACES2065-1 (AP0) linear ─ clamp to AP1 [0, forward_limit]
//!   → Hellwig 2022 JMh (input CAM params)
//!   → tonescale J  +  chroma compression of M
//!   → gamut compression of (J, M) to the limiting display's hull
//!   → JMh → display-linear RGB in the limiting primaries, 1.0 = 100 cd/m²
//! ```
//!
//! Display encoding (sRGB / BT.1886 / PQ / HLG OETFs) is out of scope here —
//! zentone's `pipeline` and `linear-srgb` handle that. The transform also
//! exposes [`Aces2OutputTransform::inverse`] (display-linear → AP0), which
//! matches the CTL `outputTransform_inv`.
//!
//! **Parity.** The forward stages are held to OpenColorIO 2.5's built-in
//! ACES 2.0 fixed functions (`reference-checks/golden/aces2_ocio_*.csv`,
//! generated by `reference-checks/aces2_ocio_reference.py`) in the unit
//! tests at the bottom of this file. Two deliberate deviations from the CTL
//! text, both matching OpenColorIO: the upper-hull gamma interpolation weight
//! is normalised by the hue interval width (`(h - h_lo) / (h_hi - h_lo)`; the
//! CTL's `interpolation_weight` returns the un-normalised `h - h_lo`, which
//! is only exact for the 1° intervals), and hue is looked up against the
//! 360-entry nominal table rather than the 362-entry padded one.
//!
//! **Cost.** Per pixel: two CAM transforms (4 `pow`), the tonescale (2
//! `pow`), and the compression math — scalar only in this first cut, no SIMD
//! strip kernel. Construction builds three 360-entry hue tables by bisection
//! (reach M, display cusp, upper-hull gamma), on the order of 10⁵ CAM
//! evaluations; build one transform per output configuration and reuse it.

use alloc::boxed::Box;

use crate::{Error, Result, ToneMap};
use libm::{atan2f, cosf, fabsf, fmodf, log10f, logf, powf, roundf, sinf, sqrtf};

// ---------------------------------------------------------------------------
// Constants (Lib.Academy.OutputTransform.ctl)
// ---------------------------------------------------------------------------

const REF_LUMINANCE: f32 = 100.0;
const L_A: f32 = 100.0;
const Y_B: f32 = 20.0;
/// Dim surround.
const SURROUND: [f32; 3] = [0.9, 0.59, 0.9];
const J_SCALE: f32 = 100.0;
const CAM_NL_OFFSET: f32 = 0.2713 * 100.0;
const CAM_NL_SCALE: f32 = 4.0 * 100.0;

// Chroma compression.
const CHROMA_COMPRESS: f32 = 2.4;
const CHROMA_COMPRESS_FACT: f32 = 3.3;
const CHROMA_EXPAND: f32 = 1.3;
const CHROMA_EXPAND_FACT: f32 = 0.69;
const CHROMA_EXPAND_THR: f32 = 0.5;

// Gamut compression.
const SMOOTH_CUSPS: f32 = 0.12;
const SMOOTH_M: f32 = 0.27;
const CUSP_MID_BLEND: f32 = 1.3;
const FOCUS_GAIN_BLEND: f32 = 0.3;
const FOCUS_DISTANCE: f32 = 1.35;
const FOCUS_DISTANCE_SCALING: f32 = 1.75;
const COMPRESSION_THRESHOLD: f32 = 0.75;

// Tables.
const TABLE_SIZE: usize = 360;
const BASE_INDEX: usize = 1;
/// One wrap entry below, one above the 360 nominal entries.
const TOTAL_TABLE_SIZE: usize = TABLE_SIZE + 2;
const HUE_LIMIT: f32 = 360.0;
const CUSP_CORNER_COUNT: usize = 6;
const TOTAL_CORNER_COUNT: usize = CUSP_CORNER_COUNT + 2;
const MAX_SORTED_CORNERS: usize = 2 * CUSP_CORNER_COUNT;
const REACH_CUSP_TOLERANCE: f32 = 1e-3;
const DISPLAY_CUSP_TOLERANCE: f32 = 1e-7;
const GAMMA_MINIMUM: f32 = 0.0;
const GAMMA_MAXIMUM: f32 = 5.0;
const GAMMA_SEARCH_STEP: f32 = 0.4;
const GAMMA_ACCURACY: f32 = 1e-5;

const PI: f32 = core::f32::consts::PI;

fn model_gamma() -> f32 {
    SURROUND[1] * (1.48 + sqrtf(Y_B / REF_LUMINANCE))
}

// ---------------------------------------------------------------------------
// Chromaticities & matrices (row-vector convention, as in the CTL:
// `out = v · M`, `out[j] = Σ_i v[i]·M[i][j]`)
// ---------------------------------------------------------------------------

/// CIE xy chromaticities of an RGB colour space's primaries and white point.
///
/// Used to pick the ACES 2.0 *limiting* (display) gamut. The constants cover
/// the display targets the ACES output presets ship, plus AP0/AP1.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Chromaticities {
    /// Red primary `[x, y]`.
    pub red: [f32; 2],
    /// Green primary `[x, y]`.
    pub green: [f32; 2],
    /// Blue primary `[x, y]`.
    pub blue: [f32; 2],
    /// White point `[x, y]`.
    pub white: [f32; 2],
}

impl Chromaticities {
    /// ACES AP0 (SMPTE ST 2065-1), ACES white (~D60).
    pub const AP0: Self = Self {
        red: [0.73470, 0.26530],
        green: [0.00000, 1.00000],
        blue: [0.00010, -0.07700],
        white: [0.32168, 0.33767],
    };
    /// ACES AP1 (ACEScg), ACES white (~D60).
    pub const AP1: Self = Self {
        red: [0.713, 0.293],
        green: [0.165, 0.830],
        blue: [0.128, 0.044],
        white: [0.32168, 0.33767],
    };
    /// ITU-R BT.709 / sRGB, D65.
    pub const REC709: Self = Self {
        red: [0.640, 0.330],
        green: [0.300, 0.600],
        blue: [0.150, 0.060],
        white: [0.3127, 0.3290],
    };
    /// P3 primaries with a D65 white (Display P3).
    pub const P3_D65: Self = Self {
        red: [0.680, 0.320],
        green: [0.265, 0.690],
        blue: [0.150, 0.060],
        white: [0.3127, 0.3290],
    };
    /// ITU-R BT.2020 / BT.2100, D65.
    pub const REC2020: Self = Self {
        red: [0.708, 0.292],
        green: [0.170, 0.797],
        blue: [0.131, 0.046],
        white: [0.3127, 0.3290],
    };
}

type Mat3 = [[f32; 3]; 3];

const IDENTITY: Mat3 = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]];

#[inline]
fn mul_vm(v: [f32; 3], m: &Mat3) -> [f32; 3] {
    [
        v[0] * m[0][0] + v[1] * m[1][0] + v[2] * m[2][0],
        v[0] * m[0][1] + v[1] * m[1][1] + v[2] * m[2][1],
        v[0] * m[0][2] + v[1] * m[1][2] + v[2] * m[2][2],
    ]
}

fn mul_mm(a: &Mat3, b: &Mat3) -> Mat3 {
    let mut r = [[0.0f32; 3]; 3];
    for (i, row) in r.iter_mut().enumerate() {
        for (j, cell) in row.iter_mut().enumerate() {
            *cell = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
        }
    }
    r
}

fn scale_m(m: &Mat3, s: f32) -> Mat3 {
    let mut r = *m;
    for row in r.iter_mut() {
        for cell in row.iter_mut() {
            *cell *= s;
        }
    }
    r
}

fn scale_diagonal(m: &Mat3, v: [f32; 3]) -> Mat3 {
    let mut r = *m;
    r[0][0] *= v[0];
    r[1][1] *= v[1];
    r[2][2] *= v[2];
    r
}

fn invert(m: &Mat3) -> Option<Mat3> {
    let c00 = m[1][1] * m[2][2] - m[1][2] * m[2][1];
    let c01 = m[1][2] * m[2][0] - m[1][0] * m[2][2];
    let c02 = m[1][0] * m[2][1] - m[1][1] * m[2][0];
    let det = m[0][0] * c00 + m[0][1] * c01 + m[0][2] * c02;
    if det == 0.0 || !det.is_finite() {
        return None;
    }
    let inv_det = 1.0 / det;
    Some([
        [
            c00 * inv_det,
            (m[0][2] * m[2][1] - m[0][1] * m[2][2]) * inv_det,
            (m[0][1] * m[1][2] - m[0][2] * m[1][1]) * inv_det,
        ],
        [
            c01 * inv_det,
            (m[0][0] * m[2][2] - m[0][2] * m[2][0]) * inv_det,
            (m[0][2] * m[1][0] - m[0][0] * m[1][2]) * inv_det,
        ],
        [
            c02 * inv_det,
            (m[0][1] * m[2][0] - m[0][0] * m[2][1]) * inv_det,
            (m[0][0] * m[1][1] - m[0][1] * m[1][0]) * inv_det,
        ],
    ])
}

/// `RGBtoXYZ_f33(C, Y)` from `Lib.Academy.Utilities.ctl`.
fn rgb_to_xyz_matrix(c: &Chromaticities, y: f32) -> Mat3 {
    let x = c.white[0] * y / c.white[1];
    let z = (1.0 - c.white[0] - c.white[1]) * y / c.white[1];
    let d = c.red[0] * (c.blue[1] - c.green[1])
        + c.blue[0] * (c.green[1] - c.red[1])
        + c.green[0] * (c.red[1] - c.blue[1]);
    let sr = (x * (c.blue[1] - c.green[1])
        - c.green[0] * (y * (c.blue[1] - 1.0) + c.blue[1] * (x + z))
        + c.blue[0] * (y * (c.green[1] - 1.0) + c.green[1] * (x + z)))
        / d;
    let sg = (x * (c.red[1] - c.blue[1])
        + c.red[0] * (y * (c.blue[1] - 1.0) + c.blue[1] * (x + z))
        - c.blue[0] * (y * (c.red[1] - 1.0) + c.red[1] * (x + z)))
        / d;
    let sb = (x * (c.green[1] - c.red[1])
        - c.red[0] * (y * (c.green[1] - 1.0) + c.green[1] * (x + z))
        + c.green[0] * (y * (c.red[1] - 1.0) + c.red[1] * (x + z)))
        / d;
    [
        [
            sr * c.red[0],
            sr * c.red[1],
            sr * (1.0 - c.red[0] - c.red[1]),
        ],
        [
            sg * c.green[0],
            sg * c.green[1],
            sg * (1.0 - c.green[0] - c.green[1]),
        ],
        [
            sb * c.blue[0],
            sb * c.blue[1],
            sb * (1.0 - c.blue[0] - c.blue[1]),
        ],
    ]
}

fn xyz_to_rgb_matrix(c: &Chromaticities, y: f32) -> Option<Mat3> {
    invert(&rgb_to_xyz_matrix(c, y))
}

#[inline]
fn lerp(a: f32, b: f32, t: f32) -> f32 {
    a + t * (b - a)
}

#[inline]
fn copysign(x: f32, y: f32) -> f32 {
    // CTL `copysign` returns 0 for y == 0 (sign(0) == 0); OpenColorIO uses
    // `std::copysign`, which keeps the magnitude. Only reachable with an
    // exactly-zero cone response, where the magnitude is 0 either way.
    libm::copysignf(x, y)
}

#[inline]
fn wrap_to_360(h: f32) -> f32 {
    let y = fmodf(h, HUE_LIMIT);
    if y < 0.0 { y + HUE_LIMIT } else { y }
}

// ---------------------------------------------------------------------------
// Hellwig 2022 CAM (JMh)
// ---------------------------------------------------------------------------

/// Pre-computed CAM matrices and constants for one set of primaries.
#[derive(Debug, Clone, Copy)]
struct JmhParams {
    rgb_to_cam16_c: Mat3,
    cam16_c_to_rgb: Mat3,
    cone_response_to_aab: Mat3,
    aab_to_cone_response: Mat3,
    f_l_n: f32,
    cz: f32,
    inv_cz: f32,
    a_w_j: f32,
    inv_a_w_j: f32,
}

#[inline]
fn cone_compress_fwd_abs(rc: f32) -> f32 {
    let f_l_y = powf(rc, 0.42);
    f_l_y / (CAM_NL_OFFSET + f_l_y)
}

#[inline]
fn cone_compress_inv_abs(ra: f32) -> f32 {
    let ra_lim = ra.min(0.99);
    let f_l_y = (CAM_NL_OFFSET * ra_lim) / (1.0 - ra_lim);
    powf(f_l_y, 1.0 / 0.42)
}

#[inline]
fn cone_compress_fwd(v: f32) -> f32 {
    copysign(cone_compress_fwd_abs(fabsf(v)), v)
}

#[inline]
fn cone_compress_inv(v: f32) -> f32 {
    copysign(cone_compress_inv_abs(fabsf(v)), v)
}

#[inline]
fn achromatic_n_to_j(a: f32, cz: f32) -> f32 {
    J_SCALE * powf(a, cz)
}

#[inline]
fn j_to_achromatic_n(j: f32, inv_cz: f32) -> f32 {
    powf(j * (1.0 / J_SCALE), inv_cz)
}

impl JmhParams {
    /// `init_JMhParams(prims)`.
    fn new(prims: &Chromaticities) -> Option<Self> {
        const CAM16_PRI: Chromaticities = Chromaticities {
            red: [0.8336, 0.1735],
            green: [2.3854, -1.4659],
            blue: [0.087, -0.125],
            white: [0.333, 0.333],
        };
        let matrix_16 = xyz_to_rgb_matrix(&CAM16_PRI, 1.0)?;
        let base_cone_response_to_aab: Mat3 = [
            [2.0, 1.0, 1.0 / 9.0],
            [1.0, -12.0 / 11.0, 1.0 / 9.0],
            [1.0 / 20.0, 1.0 / 11.0, -2.0 / 9.0],
        ];
        let rgb_to_xyz = rgb_to_xyz_matrix(prims, 1.0);
        let xyz_w = mul_vm([REF_LUMINANCE; 3], &rgb_to_xyz);
        let y_w = xyz_w[1];
        let rgb_w = mul_vm(xyz_w, &matrix_16);

        let k = 1.0 / (5.0 * L_A + 1.0);
        let k4 = k * k * k * k;
        let f_l = 0.2 * k4 * (5.0 * L_A) + 0.1 * powf(1.0 - k4, 2.0) * powf(5.0 * L_A, 1.0 / 3.0);
        let f_l_n = f_l / REF_LUMINANCE;
        let cz = model_gamma();

        let d_rgb = [
            f_l_n * y_w / rgb_w[0],
            f_l_n * y_w / rgb_w[1],
            f_l_n * y_w / rgb_w[2],
        ];
        let rgb_wc = [
            d_rgb[0] * rgb_w[0],
            d_rgb[1] * rgb_w[1],
            d_rgb[2] * rgb_w[2],
        ];
        let rgb_aw = [
            cone_compress_fwd(rgb_wc[0]),
            cone_compress_fwd(rgb_wc[1]),
            cone_compress_fwd(rgb_wc[2]),
        ];
        let cone_response_to_aab = mul_mm(
            &scale_m(&IDENTITY, CAM_NL_SCALE),
            &base_cone_response_to_aab,
        );
        let a_w = cone_response_to_aab[0][0] * rgb_aw[0]
            + cone_response_to_aab[1][0] * rgb_aw[1]
            + cone_response_to_aab[2][0] * rgb_aw[2];
        let a_w_j = cone_compress_fwd_abs(f_l);

        // Prescale the CAM16 LMS responses to provide chromatic adaptation.
        let m1 = mul_mm(&rgb_to_xyz, &matrix_16);
        let m2 = scale_m(&IDENTITY, REF_LUMINANCE);
        let rgb_to_cam16 = mul_mm(&m1, &m2);
        let rgb_to_cam16_c = mul_mm(&rgb_to_cam16, &scale_diagonal(&IDENTITY, d_rgb));

        let s = 43.0 * SURROUND[2];
        let c2a = &cone_response_to_aab;
        let cone_response_to_aab_n: Mat3 = [
            [c2a[0][0] / a_w, c2a[0][1] * s, c2a[0][2] * s],
            [c2a[1][0] / a_w, c2a[1][1] * s, c2a[1][2] * s],
            [c2a[2][0] / a_w, c2a[2][1] * s, c2a[2][2] * s],
        ];

        Some(Self {
            rgb_to_cam16_c,
            cam16_c_to_rgb: invert(&rgb_to_cam16_c)?,
            cone_response_to_aab: cone_response_to_aab_n,
            aab_to_cone_response: invert(&cone_response_to_aab_n)?,
            f_l_n,
            cz,
            inv_cz: 1.0 / cz,
            a_w_j,
            inv_a_w_j: 1.0 / a_w_j,
        })
    }

    #[inline]
    fn a_to_y(&self, a: f32) -> f32 {
        cone_compress_inv_abs(self.a_w_j * a) / self.f_l_n
    }

    #[inline]
    fn j_to_y(&self, j: f32) -> f32 {
        self.a_to_y(j_to_achromatic_n(fabsf(j), self.inv_cz))
    }

    #[inline]
    fn y_to_j(&self, y: f32) -> f32 {
        let ra = cone_compress_fwd_abs(fabsf(y) * self.f_l_n);
        copysign(achromatic_n_to_j(ra * self.inv_a_w_j, self.cz), y)
    }

    #[inline]
    fn rgb_to_aab(&self, rgb: [f32; 3]) -> [f32; 3] {
        let rgb_m = mul_vm(rgb, &self.rgb_to_cam16_c);
        let rgb_a = [
            cone_compress_fwd(rgb_m[0]),
            cone_compress_fwd(rgb_m[1]),
            cone_compress_fwd(rgb_m[2]),
        ];
        mul_vm(rgb_a, &self.cone_response_to_aab)
    }

    #[inline]
    fn aab_to_jmh(&self, aab: [f32; 3]) -> [f32; 3] {
        if aab[0] <= 0.0 {
            return [0.0, 0.0, 0.0];
        }
        let j = achromatic_n_to_j(aab[0], self.cz);
        let m = sqrtf(aab[1] * aab[1] + aab[2] * aab[2]);
        let h = wrap_to_360(atan2f(aab[2], aab[1]) * 180.0 / PI);
        [j, m, h]
    }

    #[inline]
    fn rgb_to_jmh(&self, rgb: [f32; 3]) -> [f32; 3] {
        self.aab_to_jmh(self.rgb_to_aab(rgb))
    }

    #[inline]
    fn jmh_to_aab(&self, jmh: [f32; 3]) -> [f32; 3] {
        let h_rad = jmh[2] / 180.0 * PI;
        let a = j_to_achromatic_n(jmh[0], self.inv_cz);
        [a, jmh[1] * cosf(h_rad), jmh[1] * sinf(h_rad)]
    }

    #[inline]
    fn aab_to_rgb(&self, aab: [f32; 3]) -> [f32; 3] {
        let rgb_a = mul_vm(aab, &self.aab_to_cone_response);
        let rgb_m = [
            cone_compress_inv(rgb_a[0]),
            cone_compress_inv(rgb_a[1]),
            cone_compress_inv(rgb_a[2]),
        ];
        mul_vm(rgb_m, &self.cam16_c_to_rgb)
    }

    #[inline]
    fn jmh_to_rgb(&self, jmh: [f32; 3]) -> [f32; 3] {
        self.aab_to_rgb(self.jmh_to_aab(jmh))
    }
}

// ---------------------------------------------------------------------------
// Tonescale (Lib.Academy.Tonescale.ctl)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy)]
struct TsParams {
    n: f32,
    n_r: f32,
    g: f32,
    t_1: f32,
    c_t: f32,
    s_2: f32,
    u_2: f32,
    m_2: f32,
    forward_limit: f32,
    log_peak: f32,
}

impl TsParams {
    /// `init_TSParams(peakLuminance)`.
    fn new(peak_luminance: f32) -> Self {
        let n = peak_luminance;
        let n_r = 100.0; // normalized white in nits (what 1.0 should be)
        let g = 1.15; // surround / contrast
        let c = 0.18; // anchor for 18% grey
        let c_d = 10.013; // output luminance of 18% grey (in nits)
        let w_g = 0.14; // change in grey between different peak luminance
        let t_1 = 0.04; // shadow toe or flare/glare compensation
        let r_hit_min = 128.0; // scene-referred value "hitting the roof" for SDR
        let r_hit_max = 896.0; // ... for 10000 nits

        let r_hit = r_hit_min + (r_hit_max - r_hit_min) * (logf(n / n_r) / logf(10000.0 / 100.0));
        let m_0 = n / n_r;
        let m_1 = 0.5 * (m_0 + sqrtf(m_0 * (m_0 + 4.0 * t_1)));
        let u = powf((r_hit / m_1) / ((r_hit / m_1) + 1.0), g);
        let m = m_1 / u;
        let w_i = logf(n / 100.0) / logf(2.0);
        let c_t = c_d / n_r * (1.0 + w_i * w_g);
        let g_ip = 0.5 * (c_t + sqrtf(c_t * (c_t + 4.0 * t_1)));
        let g_ipp2 = -(m_1 * powf(g_ip / m, 1.0 / g)) / (powf(g_ip / m, 1.0 / g) - 1.0);
        let w_2 = c / g_ipp2;
        let s_2 = w_2 * m_1;
        let u_2 = powf((r_hit / m_1) / ((r_hit / m_1) + w_2), g);
        let m_2 = m_1 / u_2;

        Self {
            n,
            n_r,
            g,
            t_1,
            c_t,
            s_2,
            u_2,
            m_2,
            forward_limit: 8.0 * r_hit,
            log_peak: log10f(n / n_r),
        }
    }

    /// `tonescale_fwd`: scene-referred linear (1.0 = 100 nits) → cd/m².
    #[inline]
    fn fwd(&self, x: f32) -> f32 {
        let f = self.m_2 * powf(x.max(0.0) / (x + self.s_2), self.g);
        let h = (f * f / (f + self.t_1)).max(0.0);
        h * self.n_r
    }

    /// `tonescale_inv`: cd/m² → scene-referred linear.
    #[inline]
    fn inv(&self, y: f32) -> f32 {
        let z = y.min(self.n / (self.u_2 * self.n_r)).max(0.0);
        let h = (z + sqrtf(z * (4.0 * self.t_1 + z))) / 2.0;
        self.s_2 / (powf(self.m_2 / h, 1.0 / self.g) - 1.0)
    }
}

// ---------------------------------------------------------------------------
// Chroma compression
// ---------------------------------------------------------------------------

#[inline]
fn chroma_compress_norm(h: f32, chroma_compress_scale: f32) -> f32 {
    let hr = h / 180.0 * PI;
    let a = cosf(hr);
    let b = sinf(hr);
    let cos_hr2 = a * a - b * b;
    let sin_hr2 = 2.0 * a * b;
    let cos_hr3 = 4.0 * a * a * a - 3.0 * a;
    let sin_hr3 = 3.0 * b - 4.0 * b * b * b;
    let m = 11.34072 * a + 16.46899 * cos_hr2 + 7.88380 * cos_hr3 + 14.66441 * b
        - 6.37224 * sin_hr2
        + 9.19364 * sin_hr3
        + 77.12896;
    m * chroma_compress_scale
}

/// A "toe" that remaps `x` between 0 and `limit`
/// (<https://www.desmos.com/calculator/6vplvw14ti>).
#[inline]
fn toe(x: f32, limit: f32, k1_in: f32, k2_in: f32, invert: bool) -> f32 {
    if x > limit {
        return x;
    }
    let k2 = k2_in.max(0.001);
    let k1 = sqrtf(k1_in * k1_in + k2 * k2);
    let k3 = (limit + k1) / (limit + k2);
    if invert {
        (x * x + k1 * x) / (k3 * (x + k2))
    } else {
        let minus_b = k3 * x - k1;
        let minus_c = k2 * k3 * x;
        0.5 * (minus_b + sqrtf(minus_b * minus_b + 4.0 * minus_c))
    }
}

// ---------------------------------------------------------------------------
// Gamut compression — per-pixel math
// ---------------------------------------------------------------------------

#[inline]
fn compute_compression_vector_slope(
    intersect_j: f32,
    focus_j: f32,
    limit_j_max: f32,
    slope_gain: f32,
) -> f32 {
    let direction_scalar = if intersect_j < focus_j {
        intersect_j
    } else {
        limit_j_max - intersect_j
    };
    direction_scalar * (intersect_j - focus_j) / (focus_j * slope_gain)
}

#[inline]
fn solve_j_intersect(j: f32, m: f32, focus_j: f32, max_j: f32, slope_gain: f32) -> f32 {
    let m_scaled = m / slope_gain;
    let a = m_scaled / focus_j;
    if j < focus_j {
        let b = 1.0 - m_scaled;
        let c = -j;
        let det = b * b - 4.0 * a * c;
        let root = sqrtf(det);
        -2.0 * c / (b + root)
    } else {
        let b = -(1.0 + m_scaled + max_j * a);
        let c = max_j * m_scaled + j;
        let det = b * b - 4.0 * a * c;
        let root = sqrtf(det);
        -2.0 * c / (b - root)
    }
}

/// Smooth minimum about the scaled reference (cubic polynomial).
#[inline]
fn smin_scaled(a: f32, b: f32, scale_reference: f32) -> f32 {
    let s_scaled = SMOOTH_CUSPS * scale_reference;
    let h = (s_scaled - fabsf(a - b)).max(0.0) / s_scaled;
    a.min(b) - h * h * h * s_scaled * (1.0 / 6.0)
}

#[inline]
fn estimate_line_and_boundary_intersection_m(
    j_axis_intersect: f32,
    slope: f32,
    inv_gamma: f32,
    j_max: f32,
    m_max: f32,
    j_intersection_reference: f32,
) -> f32 {
    let normalised_j = j_axis_intersect / j_intersection_reference;
    let shifted_intersection = j_intersection_reference * powf(normalised_j, inv_gamma);
    shifted_intersection * m_max / (j_max - slope * m_max)
}

#[inline]
fn find_gamut_boundary_intersection(
    jm_cusp: [f32; 2],
    j_max: f32,
    gamma_top_inv: f32,
    gamma_bottom_inv: f32,
    j_intersect_source: f32,
    slope: f32,
    j_intersect_cusp: f32,
) -> f32 {
    let m_boundary_lower = estimate_line_and_boundary_intersection_m(
        j_intersect_source,
        slope,
        gamma_bottom_inv,
        jm_cusp[0],
        jm_cusp[1],
        j_intersect_cusp,
    );
    // The upper hull is flipped ('zeroed' at J_max) and the slope negated.
    let m_boundary_upper = estimate_line_and_boundary_intersection_m(
        j_max - j_intersect_source,
        -slope,
        gamma_top_inv,
        j_max - jm_cusp[0],
        jm_cusp[1],
        j_max - j_intersect_cusp,
    );
    smin_scaled(m_boundary_lower, m_boundary_upper, jm_cusp[1])
}

#[inline]
fn get_focus_gain(j: f32, analytical_threshold: f32, limit_j_max: f32, focus_dist: f32) -> f32 {
    let mut gain = limit_j_max * focus_dist;
    if j > analytical_threshold {
        // Approximate inverse required above threshold due to the
        // introduction of J in the calculation.
        let mut gain_adjustment =
            log10f((limit_j_max - analytical_threshold) / (limit_j_max - j).max(0.0001));
        gain_adjustment = gain_adjustment * gain_adjustment + 1.0;
        gain *= gain_adjustment;
    }
    gain
}

#[inline]
fn reinhard_remap(scale: f32, nd: f32, invert: bool) -> f32 {
    if invert {
        if nd >= 1.0 {
            scale
        } else {
            scale * -(nd / (nd - 1.0))
        }
    } else {
        scale * nd / (1.0 + nd)
    }
}

#[inline]
fn remap_m(m: f32, gamut_boundary_m: f32, reach_boundary_m: f32, invert: bool) -> f32 {
    let boundary_ratio = gamut_boundary_m / reach_boundary_m;
    let proportion = boundary_ratio.max(COMPRESSION_THRESHOLD);
    let threshold = proportion * gamut_boundary_m;
    if m <= threshold || proportion >= 1.0 {
        return m;
    }
    let m_offset = m - threshold;
    let gamut_offset = gamut_boundary_m - threshold;
    let reach_offset = reach_boundary_m - threshold;
    let scale = reach_offset / ((reach_offset / gamut_offset) - 1.0);
    let nd = m_offset / scale;
    threshold + reinhard_remap(scale, nd, invert)
}

#[inline]
fn compute_focus_j(cusp_j: f32, mid_j: f32, limit_j_max: f32) -> f32 {
    lerp(
        cusp_j,
        mid_j,
        (CUSP_MID_BLEND - (cusp_j / limit_j_max)).min(1.0),
    )
}

#[derive(Debug, Clone, Copy)]
struct HueDependentGamutParams {
    jm_cusp: [f32; 2],
    gamma_bottom_inv: f32,
    gamma_top_inv: f32,
    focus_j: f32,
    analytical_threshold: f32,
}

// ---------------------------------------------------------------------------
// Table generation
// ---------------------------------------------------------------------------

/// R, Y, G, C, B, M — hues rotate in order.
#[inline]
fn generate_unit_cube_cusp_corners(corner: usize) -> [f32; 3] {
    let f = |v: usize| if v % CUSP_CORNER_COUNT < 3 { 1.0 } else { 0.0 };
    [f(corner + 1), f(corner + 5), f(corner + 3)]
}

fn scale3(s: f32, v: [f32; 3]) -> [f32; 3] {
    [s * v[0], s * v[1], s * v[2]]
}

fn lerp3(a: [f32; 3], b: [f32; 3], t: f32) -> [f32; 3] {
    [
        lerp(a[0], b[0], t),
        lerp(a[1], b[1], t),
        lerp(a[2], b[2], t),
    ]
}

/// Rotate six corners so the lowest hue sits at `[1]`, and pad with wrapped
/// copies at `[0]` (hue − 360) and `[7]` (hue + 360).
fn arrange_corners(
    temp_rgb: &[[f32; 3]; CUSP_CORNER_COUNT],
    temp_jmh: &[[f32; 3]; CUSP_CORNER_COUNT],
) -> (
    [[f32; 3]; TOTAL_CORNER_COUNT],
    [[f32; 3]; TOTAL_CORNER_COUNT],
) {
    let mut min_index = 0;
    for (i, c) in temp_jmh.iter().enumerate() {
        if c[2] < temp_jmh[min_index][2] {
            min_index = i;
        }
    }
    let mut rgb = [[0.0f32; 3]; TOTAL_CORNER_COUNT];
    let mut jmh = [[0.0f32; 3]; TOTAL_CORNER_COUNT];
    for i in 0..CUSP_CORNER_COUNT {
        rgb[i + 1] = temp_rgb[(i + min_index) % CUSP_CORNER_COUNT];
        jmh[i + 1] = temp_jmh[(i + min_index) % CUSP_CORNER_COUNT];
    }
    rgb[0] = rgb[CUSP_CORNER_COUNT];
    rgb[CUSP_CORNER_COUNT + 1] = rgb[1];
    jmh[0] = jmh[CUSP_CORNER_COUNT];
    jmh[CUSP_CORNER_COUNT + 1] = jmh[1];
    jmh[0][2] -= HUE_LIMIT;
    jmh[CUSP_CORNER_COUNT + 1][2] += HUE_LIMIT;
    (rgb, jmh)
}

/// `build_limiting_cusp_corners_tables`.
fn build_limiting_cusp_corners_tables(
    params: &JmhParams,
    peak_luminance: f32,
) -> (
    [[f32; 3]; TOTAL_CORNER_COUNT],
    [[f32; 3]; TOTAL_CORNER_COUNT],
) {
    let mut temp_rgb = [[0.0f32; 3]; CUSP_CORNER_COUNT];
    let mut temp_jmh = [[0.0f32; 3]; CUSP_CORNER_COUNT];
    for i in 0..CUSP_CORNER_COUNT {
        temp_rgb[i] = scale3(
            peak_luminance / REF_LUMINANCE,
            generate_unit_cube_cusp_corners(i),
        );
        temp_jmh[i] = params.rgb_to_jmh(temp_rgb[i]);
    }
    arrange_corners(&temp_rgb, &temp_jmh)
}

/// `find_reach_corners_table`: the JMh of each unit-cube corner scaled to
/// hit `limit_j`, found by bisection on the achromatic response.
fn find_reach_corners_table(
    params_reach: &JmhParams,
    limit_j_max: f32,
    forward_limit: f32,
) -> [[f32; 3]; TOTAL_CORNER_COUNT] {
    let limit_a = j_to_achromatic_n(limit_j_max, params_reach.inv_cz);
    let mut temp_jmh = [[0.0f32; 3]; CUSP_CORNER_COUNT];
    let temp_rgb = [[0.0f32; 3]; CUSP_CORNER_COUNT];
    for (i, out) in temp_jmh.iter_mut().enumerate() {
        let rgb_vector = generate_unit_cube_cusp_corners(i);
        let mut lower = 0.0f32;
        let mut upper = forward_limit;
        while (upper - lower) > REACH_CUSP_TOLERANCE {
            let test = (lower + upper) / 2.0;
            let a = params_reach.rgb_to_aab(scale3(test, rgb_vector))[0];
            if a < limit_a {
                lower = test;
            } else {
                upper = test;
            }
            if a == limit_a {
                break;
            }
        }
        *out = params_reach.rgb_to_jmh(scale3(upper, rgb_vector));
    }
    arrange_corners(&temp_rgb, &temp_jmh).1
}

/// Merge the two sorted corner-hue lists (entries `1..=6`), de-duplicating
/// equal hues. Returns the hues and the unique count.
fn extract_sorted_cube_hues(
    reach_jmh: &[[f32; 3]; TOTAL_CORNER_COUNT],
    limit_jmh: &[[f32; 3]; TOTAL_CORNER_COUNT],
) -> ([f32; MAX_SORTED_CORNERS], usize) {
    let mut sorted = [0.0f32; MAX_SORTED_CORNERS];
    let mut idx = 0;
    let mut reach_idx = 1;
    let mut limit_idx = 1;
    while reach_idx < CUSP_CORNER_COUNT + 1 || limit_idx < CUSP_CORNER_COUNT + 1 {
        // Index 7 holds the +360°-wrapped first hue, which acts as a sentinel
        // once one list is exhausted.
        let reach_hue = reach_jmh[reach_idx][2];
        let limit_hue = limit_jmh[limit_idx][2];
        if reach_hue == limit_hue {
            sorted[idx] = reach_hue;
            reach_idx += 1;
            limit_idx += 1;
        } else if reach_hue < limit_hue {
            sorted[idx] = reach_hue;
            reach_idx += 1;
        } else {
            sorted[idx] = limit_hue;
            limit_idx += 1;
        }
        idx += 1;
    }
    (sorted, idx)
}

fn build_hue_sample_interval(
    hue_table: &mut [f32; TOTAL_TABLE_SIZE],
    samples: usize,
    lower: f32,
    upper: f32,
    base: usize,
) {
    let delta = (upper - lower) / samples as f32;
    for i in 0..samples {
        hue_table[base + i] = lower + i as f32 * delta;
    }
}

/// `build_hue_table`: 360 hues, as uniform as possible while landing exactly
/// on every gamut corner hue.
fn build_hue_table(
    sorted_hues: &[f32; MAX_SORTED_CORNERS],
    unique_hues: usize,
) -> [f32; TOTAL_TABLE_SIZE] {
    let mut hue_table = [0.0f32; TOTAL_TABLE_SIZE];
    let ideal_spacing = TABLE_SIZE as f32 / HUE_LIMIT;
    let mut samples_count = [0usize; MAX_SORTED_CORNERS + 2];
    let mut last_idx = usize::MAX;
    // Ensure we can always sample at hue 0.
    let mut min_index = if sorted_hues[0] == 0.0 { 0 } else { 1 };
    for hue_idx in 0..unique_hues {
        let rounded = roundf(sorted_hues[hue_idx] * ideal_spacing).max(0.0) as usize;
        let mut nominal_idx = rounded.max(min_index).min(TABLE_SIZE - 1);
        if last_idx == nominal_idx {
            // Two hues would sample at the same index: move the previous one
            // down if there is room, otherwise this one up.
            if hue_idx > 1 && samples_count[hue_idx - 2] != samples_count[hue_idx - 1] - 1 {
                samples_count[hue_idx - 1] -= 1;
            } else {
                nominal_idx += 1;
            }
        }
        samples_count[hue_idx] = nominal_idx.min(TABLE_SIZE - 1);
        min_index = nominal_idx;
        last_idx = nominal_idx;
    }

    let mut total_samples = 0usize;
    build_hue_sample_interval(
        &mut hue_table,
        samples_count[0],
        0.0,
        sorted_hues[0],
        total_samples + 1,
    );
    total_samples += samples_count[0];
    for i in 1..unique_hues {
        let samples = samples_count[i] - samples_count[i - 1];
        build_hue_sample_interval(
            &mut hue_table,
            samples,
            sorted_hues[i - 1],
            sorted_hues[i],
            total_samples + 1,
        );
        total_samples += samples;
    }
    build_hue_sample_interval(
        &mut hue_table,
        TABLE_SIZE - total_samples,
        sorted_hues[unique_hues - 1],
        HUE_LIMIT,
        total_samples + 1,
    );

    hue_table[0] = hue_table[BASE_INDEX + TABLE_SIZE - 1] - HUE_LIMIT;
    hue_table[BASE_INDEX + TABLE_SIZE] = hue_table[BASE_INDEX] + HUE_LIMIT;
    hue_table
}

/// `find_display_cusp_for_hue`: bisect along the cube edge between the two
/// corners bracketing `hue` until the JMh hue matches.
fn find_display_cusp_for_hue(
    hue: f32,
    rgb_corners: &[[f32; 3]; TOTAL_CORNER_COUNT],
    jmh_corners: &[[f32; 3]; TOTAL_CORNER_COUNT],
    params: &JmhParams,
    previous: &mut [f32; 2],
) -> [f32; 2] {
    let mut upper_corner = 1;
    for (i, c) in jmh_corners.iter().enumerate().skip(1) {
        if c[2] > hue {
            upper_corner = i;
            break;
        }
    }
    let lower_corner = upper_corner - 1;
    if jmh_corners[lower_corner][2] == hue {
        return [jmh_corners[lower_corner][0], jmh_corners[lower_corner][1]];
    }

    let cusp_lower = rgb_corners[lower_corner];
    let cusp_upper = rgb_corners[upper_corner];
    // Still on the same edge: resume from where the previous hue ended.
    let mut lower_t = if upper_corner as f32 == previous[0] {
        previous[1]
    } else {
        0.0
    };
    let mut upper_t = 1.0f32;

    // Across the [0, 360) boundary the search directions swap; comparing
    // against the corner hues keeps the sample inside the edge's hue range.
    while (upper_t - lower_t) > DISPLAY_CUSP_TOLERANCE {
        let sample_t = (lower_t + upper_t) / 2.0;
        let jmh = params.rgb_to_jmh(lerp3(cusp_lower, cusp_upper, sample_t));
        if jmh[2] < jmh_corners[lower_corner][2] {
            upper_t = sample_t;
        } else if jmh[2] >= jmh_corners[upper_corner][2] {
            lower_t = sample_t;
        } else if jmh[2] > hue {
            upper_t = sample_t;
        } else {
            lower_t = sample_t;
        }
    }
    let sample_t = (lower_t + upper_t) / 2.0;
    let jmh = params.rgb_to_jmh(lerp3(cusp_lower, cusp_upper, sample_t));
    previous[0] = upper_corner as f32;
    previous[1] = sample_t;
    [jmh[0], jmh[1]]
}

/// `make_reach_m_table`: the reach gamut's M at `limit_j_max` per degree.
fn make_reach_m_table(params: &JmhParams, limit_j_max: f32) -> [f32; TOTAL_TABLE_SIZE] {
    let mut table = [0.0f32; TOTAL_TABLE_SIZE];
    for i in 0..TABLE_SIZE {
        let hue = i as f32 * HUE_LIMIT / TABLE_SIZE as f32;
        const SEARCH_RANGE: f32 = 50.0;
        const SEARCH_MAXIMUM: f32 = 1300.0;
        let mut low = 0.0f32;
        let mut high = low + SEARCH_RANGE;
        let mut outside = false;
        let any_below_zero = |m: f32| {
            let rgb = params.jmh_to_rgb([limit_j_max, m, hue]);
            rgb[0] < 0.0 || rgb[1] < 0.0 || rgb[2] < 0.0
        };
        while !outside && high < SEARCH_MAXIMUM {
            outside = any_below_zero(high);
            if !outside {
                low = high;
                high += SEARCH_RANGE;
            }
        }
        while high - low > 1e-2 {
            let sample_m = (high + low) / 2.0;
            if any_below_zero(sample_m) {
                high = sample_m;
            } else {
                low = sample_m;
            }
        }
        table[i + BASE_INDEX] = high;
    }
    table[0] = table[TABLE_SIZE];
    table[BASE_INDEX + TABLE_SIZE] = table[BASE_INDEX];
    table
}

const GAMMA_TEST_COUNT: usize = 5;
const GAMMA_TEST_POSITIONS: [f32; GAMMA_TEST_COUNT] = [0.01, 0.1, 0.5, 0.8, 0.99];

#[derive(Debug, Clone, Copy, Default)]
struct GammaTestData {
    j_intersect_source: f32,
    slope: f32,
    j_intersect_cusp: f32,
}

fn generate_gamma_test_data(
    jm_cusp: [f32; 2],
    limit_j_max: f32,
    mid_j: f32,
    focus_dist: f32,
) -> [GammaTestData; GAMMA_TEST_COUNT] {
    let analytical_threshold = lerp(jm_cusp[0], limit_j_max, FOCUS_GAIN_BLEND);
    let focus_j = compute_focus_j(jm_cusp[0], mid_j, limit_j_max);
    let mut data = [GammaTestData::default(); GAMMA_TEST_COUNT];
    for (d, &pos) in data.iter_mut().zip(GAMMA_TEST_POSITIONS.iter()) {
        let test_j = lerp(jm_cusp[0], limit_j_max, pos);
        let slope_gain = get_focus_gain(test_j, analytical_threshold, limit_j_max, focus_dist);
        let j_intersect_source =
            solve_j_intersect(test_j, jm_cusp[1], focus_j, limit_j_max, slope_gain);
        *d = GammaTestData {
            j_intersect_source,
            slope: compute_compression_vector_slope(
                j_intersect_source,
                focus_j,
                limit_j_max,
                slope_gain,
            ),
            j_intersect_cusp: solve_j_intersect(
                jm_cusp[0],
                jm_cusp[1],
                focus_j,
                limit_j_max,
                slope_gain,
            ),
        };
    }
    data
}

#[allow(clippy::too_many_arguments)]
fn evaluate_gamma_fit(
    jm_cusp: [f32; 2],
    hue: f32,
    data: &[GammaTestData; GAMMA_TEST_COUNT],
    top_gamma_inv: f32,
    peak_luminance: f32,
    limit_j_max: f32,
    lower_hull_gamma_inv: f32,
    limit_params: &JmhParams,
) -> bool {
    let luminance_limit = peak_luminance / REF_LUMINANCE;
    for t in data {
        let approx_limit_m = find_gamut_boundary_intersection(
            jm_cusp,
            limit_j_max,
            top_gamma_inv,
            lower_hull_gamma_inv,
            t.j_intersect_source,
            t.slope,
            t.j_intersect_cusp,
        );
        let approx_limit_j = t.j_intersect_source + t.slope * approx_limit_m;
        let rgb = limit_params.jmh_to_rgb([approx_limit_j, approx_limit_m, hue]);
        let outside_hull =
            rgb[0] > luminance_limit || rgb[1] > luminance_limit || rgb[2] > luminance_limit;
        if !outside_hull {
            return false;
        }
    }
    true
}

// ---------------------------------------------------------------------------
// The transform
// ---------------------------------------------------------------------------

/// Configuration for [`Aces2OutputTransform`].
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Aces2Config {
    /// Peak luminance of the target display in cd/m² (e.g. `100.0` for SDR,
    /// `1000.0` for a 1000-nit HDR preset). Must be finite and ≥ 1.
    pub peak_luminance: f32,
    /// Primaries and white of the target display — the *limiting* gamut the
    /// rendering is compressed into and the space the output is encoded in.
    pub limiting_primaries: Chromaticities,
}

impl Default for Aces2Config {
    /// 100 cd/m² Rec.709 — the SDR video preset.
    fn default() -> Self {
        Self {
            peak_luminance: 100.0,
            limiting_primaries: Chromaticities::REC709,
        }
    }
}

/// Hue-indexed tables built at construction (`ODTParams` in the CTL).
#[derive(Debug, Clone)]
struct Tables {
    reach_m: [f32; TOTAL_TABLE_SIZE],
    hues: [f32; TOTAL_TABLE_SIZE],
    cusps: [[f32; 2]; TOTAL_TABLE_SIZE],
    upper_hull_gamma: [f32; TOTAL_TABLE_SIZE],
}

/// ACES 2.0 Output Transform: ACES2065-1 (AP0) linear in, display-linear RGB
/// in the limiting primaries out (`1.0` = 100 cd/m²).
///
/// Construct once per output configuration with [`Aces2OutputTransform::new`]
/// — building the gamut tables costs on the order of 10⁵ CAM evaluations —
/// then apply per pixel via [`forward`](Self::forward) /
/// [`inverse`](Self::inverse), or through the [`ToneMap`] trait (whose
/// `map_rgb` is `forward`).
///
/// Input is ACES2065-1: convert from other scene-linear encodings with a
/// primaries matrix first (e.g. via `zenpixels-convert` or
/// [`crate::gamut::apply_matrix`]). Output is display-linear; apply the
/// display's OETF afterwards. For SDR 100-nit targets that means `1.0` is
/// diffuse white; for a 1000-nit PQ target the output reaches `10.0`.
#[derive(Debug, Clone)]
pub struct Aces2OutputTransform {
    peak_luminance: f32,
    input_params: JmhParams,
    limit_params: JmhParams,
    ts: TsParams,
    ap0_to_ap1: Mat3,
    ap1_to_ap0: Mat3,
    limit_j_max: f32,
    model_gamma_inv: f32,
    // Chroma compression.
    sat: f32,
    sat_thr: f32,
    compr: f32,
    chroma_compress_scale: f32,
    // Gamut compression.
    mid_j: f32,
    focus_dist: f32,
    lower_hull_gamma_inv: f32,
    hue_linearity_search_range: [i32; 2],
    tables: Box<Tables>,
}

impl Aces2OutputTransform {
    /// Build the transform for `config` (`init_ODTParams` in the CTL).
    ///
    /// # Errors
    ///
    /// `Error::InvalidConfig` if `peak_luminance` is not finite or below 1,
    /// or if the limiting primaries are degenerate (non-invertible).
    pub fn new(config: Aces2Config) -> Result<Self> {
        let peak = config.peak_luminance;
        if !peak.is_finite() || peak < 1.0 {
            return Err(Error::InvalidConfig(
                "ACES 2.0: peak_luminance must be finite and >= 1 cd/m^2",
            ));
        }
        let bad_prims = || Error::InvalidConfig("ACES 2.0: limiting primaries are degenerate");
        let input_params = JmhParams::new(&Chromaticities::AP0).ok_or_else(bad_prims)?;
        let reach_params = JmhParams::new(&Chromaticities::AP1).ok_or_else(bad_prims)?;
        let limit_params = JmhParams::new(&config.limiting_primaries).ok_or_else(bad_prims)?;

        let ap0_rgb_to_xyz = rgb_to_xyz_matrix(&Chromaticities::AP0, 1.0);
        let ap1_rgb_to_xyz = rgb_to_xyz_matrix(&Chromaticities::AP1, 1.0);
        let ap0_to_ap1 = mul_mm(
            &ap0_rgb_to_xyz,
            &invert(&ap1_rgb_to_xyz).ok_or_else(bad_prims)?,
        );
        let ap1_to_ap0 = mul_mm(
            &ap1_rgb_to_xyz,
            &invert(&ap0_rgb_to_xyz).ok_or_else(bad_prims)?,
        );

        let ts = TsParams::new(peak);
        let limit_j_max = input_params.y_to_j(peak);
        let model_gamma_inv = 1.0 / model_gamma();

        let reach_m = make_reach_m_table(&reach_params, limit_j_max);

        let sat = (CHROMA_EXPAND - (CHROMA_EXPAND * CHROMA_EXPAND_FACT) * ts.log_peak).max(0.2);
        let sat_thr = CHROMA_EXPAND_THR / peak;
        let compr = CHROMA_COMPRESS + (CHROMA_COMPRESS * CHROMA_COMPRESS_FACT) * ts.log_peak;
        let chroma_compress_scale = powf(0.03379 * peak, 0.30596) - 0.45135;

        let mid_j = input_params.y_to_j(ts.c_t * REF_LUMINANCE);
        let focus_dist = FOCUS_DISTANCE + FOCUS_DISTANCE * FOCUS_DISTANCE_SCALING * ts.log_peak;
        let lower_hull_gamma_inv = 1.0 / (1.14 + 0.07 * ts.log_peak);

        // Gamut cusp table on a corner-aware hue grid.
        let reach_corners = find_reach_corners_table(&reach_params, limit_j_max, ts.forward_limit);
        let (limit_rgb_corners, limit_jmh_corners) =
            build_limiting_cusp_corners_tables(&limit_params, peak);
        let (sorted_hues, unique_hues) =
            extract_sorted_cube_hues(&reach_corners, &limit_jmh_corners);
        let hues = build_hue_table(&sorted_hues, unique_hues);

        let mut cusps = [[0.0f32; 2]; TOTAL_TABLE_SIZE];
        let mut previous = [0.0f32; 2];
        for i in BASE_INDEX..BASE_INDEX + TABLE_SIZE {
            let jm = find_display_cusp_for_hue(
                hues[i],
                &limit_rgb_corners,
                &limit_jmh_corners,
                &limit_params,
                &mut previous,
            );
            cusps[i] = [jm[0], jm[1] * (1.0 + SMOOTH_M * SMOOTH_CUSPS)];
        }
        cusps[0] = cusps[TABLE_SIZE];
        cusps[BASE_INDEX + TABLE_SIZE] = cusps[BASE_INDEX];

        // Narrow the per-pixel hue search to the table's deviation from uniform.
        let mut hue_linearity_search_range = [0i32, 1];
        for (i, &h) in hues
            .iter()
            .enumerate()
            .take(BASE_INDEX + TABLE_SIZE)
            .skip(BASE_INDEX)
        {
            let pos = BASE_INDEX + (h.max(0.0) as usize).min(TABLE_SIZE - 1);
            let delta = i as i32 - pos as i32;
            hue_linearity_search_range[0] = hue_linearity_search_range[0].min(delta);
            hue_linearity_search_range[1] = hue_linearity_search_range[1].max(delta + 1);
        }

        // Upper hull gamma per hue: the smallest gamma whose analytic boundary
        // sits outside the true display hull at five test heights.
        let mut upper_hull_gamma = [0.0f32; TOTAL_TABLE_SIZE];
        for i in BASE_INDEX..BASE_INDEX + TABLE_SIZE {
            let hue = hues[i];
            let jm_cusp = cusps[i];
            let data = generate_gamma_test_data(jm_cusp, limit_j_max, mid_j, focus_dist);
            let fits = |gamma: f32| {
                evaluate_gamma_fit(
                    jm_cusp,
                    hue,
                    &data,
                    1.0 / gamma,
                    peak,
                    limit_j_max,
                    lower_hull_gamma_inv,
                    &limit_params,
                )
            };
            let mut low = GAMMA_MINIMUM;
            let mut high = low + GAMMA_SEARCH_STEP;
            let mut outside = false;
            while !outside && high < GAMMA_MAXIMUM {
                if fits(high) {
                    outside = true;
                } else {
                    low = high;
                    high += GAMMA_SEARCH_STEP;
                }
            }
            while (high - low) > GAMMA_ACCURACY {
                let test_gamma = (high + low) / 2.0;
                if fits(test_gamma) {
                    high = test_gamma;
                } else {
                    low = test_gamma;
                }
            }
            upper_hull_gamma[i] = 1.0 / high;
        }
        upper_hull_gamma[0] = upper_hull_gamma[TABLE_SIZE];
        upper_hull_gamma[BASE_INDEX + TABLE_SIZE] = upper_hull_gamma[BASE_INDEX];

        Ok(Self {
            peak_luminance: peak,
            input_params,
            limit_params,
            ts,
            ap0_to_ap1,
            ap1_to_ap0,
            limit_j_max,
            model_gamma_inv,
            sat,
            sat_thr,
            compr,
            chroma_compress_scale,
            mid_j,
            focus_dist,
            lower_hull_gamma_inv,
            hue_linearity_search_range,
            tables: Box::new(Tables {
                reach_m,
                hues,
                cusps,
                upper_hull_gamma,
            }),
        })
    }

    /// Peak display luminance this transform was built for, in cd/m².
    #[must_use]
    pub fn peak_luminance(&self) -> f32 {
        self.peak_luminance
    }

    /// Forward output transform: ACES2065-1 linear → display-linear RGB in
    /// the limiting primaries (`1.0` = 100 cd/m²).
    ///
    /// Input is first clamped to the AP1 cube `[0, forward_limit]` as the CTL
    /// does (`clamp_AP0_to_AP1`); non-finite components clamp to `0`.
    #[must_use]
    pub fn forward(&self, aces: [f32; 3]) -> [f32; 3] {
        self.forward_unclamped(self.clamp_ap0_to_ap1(aces))
    }

    /// The rendering without the AP1 clamp — what OpenColorIO's
    /// `ACES_OUTPUT_TRANSFORM_20` fixed function computes.
    fn forward_unclamped(&self, ap0: [f32; 3]) -> [f32; 3] {
        let jmh = self.input_params.rgb_to_jmh(ap0);
        let tonemapped = self.tonemap_and_compress_fwd(jmh);
        let compressed = self.gamut_compress_fwd(tonemapped);
        self.limit_params.jmh_to_rgb(compressed)
    }

    /// Inverse output transform: display-linear RGB in the limiting
    /// primaries (`1.0` = 100 cd/m²) → ACES2065-1 linear.
    ///
    /// Round-trips [`forward`](Self::forward) for colours inside the display
    /// hull; the gamut-compressed region above the analytical threshold is
    /// approximated exactly as in the CTL `outputTransform_inv`.
    #[must_use]
    pub fn inverse(&self, display_rgb: [f32; 3]) -> [f32; 3] {
        let compressed = self.limit_params.rgb_to_jmh(display_rgb);
        let tonemapped = self.gamut_compress_inv(compressed);
        let jmh = self.tonemap_and_compress_inv(tonemapped);
        self.input_params.jmh_to_rgb(jmh)
    }

    // -- stages ------------------------------------------------------------

    fn clamp_ap0_to_ap1(&self, aces: [f32; 3]) -> [f32; 3] {
        let ap1 = mul_vm(aces, &self.ap0_to_ap1);
        let lim = self.ts.forward_limit;
        // `max` then `min` so NaN lands on the lower bound.
        let c = [
            ap1[0].max(0.0).min(lim),
            ap1[1].max(0.0).min(lim),
            ap1[2].max(0.0).min(lim),
        ];
        mul_vm(c, &self.ap1_to_ap0)
    }

    /// Reach gamut M at `limit_j_max` for hue `h` (1° table, linear).
    #[inline]
    fn reach_m_from_table(&self, h: f32) -> f32 {
        let base = (h.max(0.0) as usize).min(TABLE_SIZE - 1);
        let t = h - base as f32;
        let i_lo = base + BASE_INDEX;
        lerp(self.tables.reach_m[i_lo], self.tables.reach_m[i_lo + 1], t)
    }

    /// `tonemap_and_compress_fwd`: tonescale J, then compress M.
    fn tonemap_and_compress_fwd(&self, jmh: [f32; 3]) -> [f32; 3] {
        let linear = self.input_params.j_to_y(jmh[0]) / REF_LUMINANCE;
        let tonemapped_y = self.ts.fwd(linear);
        let j_ts = self.input_params.y_to_j(tonemapped_y);
        self.chroma_compress_fwd(jmh, j_ts)
    }

    /// `tonemap_and_compress_inv`.
    fn tonemap_and_compress_inv(&self, jmh_tc: [f32; 3]) -> [f32; 3] {
        let luminance = self.input_params.j_to_y(jmh_tc[0]);
        let linear = self.ts.inv(luminance / REF_LUMINANCE);
        let j = self.input_params.y_to_j(linear * REF_LUMINANCE);
        self.chroma_compress_inv(jmh_tc, j)
    }

    /// `chroma_compress_fwd`: returns `{ tonemapped J, compressed M, h }`.
    fn chroma_compress_fwd(&self, jmh: [f32; 3], tonemapped_j: f32) -> [f32; 3] {
        let [j, m, h] = jmh;
        let mut m_compr = m;
        if m != 0.0 {
            let n_j = tonemapped_j / self.limit_j_max;
            let sn_j = (1.0 - n_j).max(0.0);
            let m_norm = chroma_compress_norm(h, self.chroma_compress_scale);
            let limit = powf(n_j, self.model_gamma_inv) * self.reach_m_from_table(h) / m_norm;
            let toe_limit = limit - 0.001;
            let toe_sn_j_sat = sn_j * self.sat;
            let toe_sqrt_n_j_sat_thr = sqrtf(n_j * n_j + self.sat_thr);
            let toe_n_j_compr = n_j * self.compr;

            // Rescale M with the tonescaled J (Hellwig model gamma keeps the
            // M/J ratio, i.e. the chromaticity, constant).
            m_compr = m * powf(tonemapped_j / j, self.model_gamma_inv);
            // Normalise by the rendering-space cusp M.
            m_compr /= m_norm;
            // Expand colourfulness (toe in reverse): shadows and mid-tones,
            // not highlights; `sat_thr` tames noise near black.
            m_compr = limit
                - toe(
                    limit - m_compr,
                    toe_limit,
                    toe_sn_j_sat,
                    toe_sqrt_n_j_sat_thr,
                    false,
                );
            // Compress: less saturated colours more, pure colours less —
            // the highlight saturation roll-off.
            m_compr = toe(m_compr, limit, toe_n_j_compr, sn_j, false);
            m_compr *= m_norm;
        }
        [tonemapped_j, m_compr, h]
    }

    /// `chroma_compress_inv`: returns `{ J, M, h }`.
    fn chroma_compress_inv(&self, jmh_tc: [f32; 3], j: f32) -> [f32; 3] {
        let [tonemapped_j, m_compr, h] = jmh_tc;
        let mut m = m_compr;
        if m_compr != 0.0 {
            let n_j = tonemapped_j / self.limit_j_max;
            let sn_j = (1.0 - n_j).max(0.0);
            let m_norm = chroma_compress_norm(h, self.chroma_compress_scale);
            let limit = powf(n_j, self.model_gamma_inv) * self.reach_m_from_table(h) / m_norm;
            let toe_limit = limit - 0.001;
            let toe_sn_j_sat = sn_j * self.sat;
            let toe_sqrt_n_j_sat_thr = sqrtf(n_j * n_j + self.sat_thr);
            let toe_n_j_compr = n_j * self.compr;

            m = m_compr / m_norm;
            m = toe(m, limit, toe_n_j_compr, sn_j, true);
            m = limit
                - toe(
                    limit - m,
                    toe_limit,
                    toe_sn_j_sat,
                    toe_sqrt_n_j_sat_thr,
                    true,
                );
            m *= m_norm;
            m *= powf(tonemapped_j / j, -self.model_gamma_inv);
        }
        [j, m, h]
    }

    /// Upper index of the hue-table interval containing `h`.
    fn lookup_hue_interval(&self, h: f32) -> usize {
        let hues = &self.tables.hues;
        let nominal = BASE_INDEX + (h.max(0.0) as usize).min(TABLE_SIZE - 1);
        let mut i = nominal;
        let mut i_lo = (nominal as i32 + self.hue_linearity_search_range[0]).max(0) as usize;
        let mut i_hi = ((nominal as i32 + self.hue_linearity_search_range[1]) as usize)
            .min(BASE_INDEX + TABLE_SIZE);
        while i_lo + 1 < i_hi {
            if h > hues[i] {
                i_lo = i;
            } else {
                i_hi = i;
            }
            i = (i_lo + i_hi) / 2;
        }
        i_hi.max(1)
    }

    fn hue_dependent_gamut_params(&self, hue: f32) -> HueDependentGamutParams {
        let i_hi = self.lookup_hue_interval(hue);
        let h_lo = self.tables.hues[i_hi - 1];
        let h_hi = self.tables.hues[i_hi];
        let t = (hue - h_lo) / (h_hi - h_lo);
        let c_lo = self.tables.cusps[i_hi - 1];
        let c_hi = self.tables.cusps[i_hi];
        let jm_cusp = [lerp(c_lo[0], c_hi[0], t), lerp(c_lo[1], c_hi[1], t)];
        HueDependentGamutParams {
            jm_cusp,
            gamma_bottom_inv: self.lower_hull_gamma_inv,
            gamma_top_inv: lerp(
                self.tables.upper_hull_gamma[i_hi - 1],
                self.tables.upper_hull_gamma[i_hi],
                t,
            ),
            focus_j: compute_focus_j(jm_cusp[0], self.mid_j, self.limit_j_max),
            analytical_threshold: lerp(jm_cusp[0], self.limit_j_max, FOCUS_GAIN_BLEND),
        }
    }

    /// `compress_gamut`.
    fn compress_gamut(
        &self,
        jmh: [f32; 3],
        jx: f32,
        hdp: &HueDependentGamutParams,
        invert: bool,
    ) -> [f32; 3] {
        let [j, m, h] = jmh;
        let slope_gain = get_focus_gain(
            jx,
            hdp.analytical_threshold,
            self.limit_j_max,
            self.focus_dist,
        );
        let j_intersect_source = solve_j_intersect(j, m, hdp.focus_j, self.limit_j_max, slope_gain);
        let gamut_slope = compute_compression_vector_slope(
            j_intersect_source,
            hdp.focus_j,
            self.limit_j_max,
            slope_gain,
        );
        let j_intersect_cusp = solve_j_intersect(
            hdp.jm_cusp[0],
            hdp.jm_cusp[1],
            hdp.focus_j,
            self.limit_j_max,
            slope_gain,
        );
        let gamut_boundary_m = find_gamut_boundary_intersection(
            hdp.jm_cusp,
            self.limit_j_max,
            hdp.gamma_top_inv,
            hdp.gamma_bottom_inv,
            j_intersect_source,
            gamut_slope,
            j_intersect_cusp,
        );
        if gamut_boundary_m <= 0.0 {
            return [j, 0.0, h];
        }
        let reach_max_m = self.reach_m_from_table(h);
        let reach_boundary_m = estimate_line_and_boundary_intersection_m(
            j_intersect_source,
            gamut_slope,
            self.model_gamma_inv,
            self.limit_j_max,
            reach_max_m,
            self.limit_j_max,
        );
        let remapped_m = remap_m(m, gamut_boundary_m, reach_boundary_m, invert);
        [j_intersect_source + remapped_m * gamut_slope, remapped_m, h]
    }

    /// `gamut_compress_fwd`.
    fn gamut_compress_fwd(&self, jmh: [f32; 3]) -> [f32; 3] {
        let [j, m, h] = jmh;
        if j <= 0.0 {
            return [0.0, 0.0, h];
        }
        if m <= 0.0 || j > self.limit_j_max {
            return [j, 0.0, h];
        }
        let hdp = self.hue_dependent_gamut_params(h);
        self.compress_gamut(jmh, j, &hdp, false)
    }

    /// `gamut_compress_inv`.
    fn gamut_compress_inv(&self, jmh: [f32; 3]) -> [f32; 3] {
        let [j, m, h] = jmh;
        if j <= 0.0 {
            return [0.0, 0.0, h];
        }
        if m <= 0.0 || j > self.limit_j_max {
            return [j, 0.0, h];
        }
        let hdp = self.hue_dependent_gamut_params(h);
        let mut jx = j;
        if jx > hdp.analytical_threshold {
            jx = self.compress_gamut(jmh, jx, &hdp, true)[0];
        }
        self.compress_gamut(jmh, jx, &hdp, true)
    }
}

impl ToneMap for Aces2OutputTransform {
    /// [`forward`](Self::forward): ACES2065-1 in, display-linear out.
    #[inline]
    fn map_rgb(&self, rgb: [f32; 3]) -> [f32; 3] {
        self.forward(rgb)
    }
}

// ---------------------------------------------------------------------------
// Tests — parity against OpenColorIO 2.5's built-in ACES 2.0 fixed functions
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec::Vec;

    const JMH_CSV: &str = include_str!("../../reference-checks/golden/aces2_ocio_jmh.csv");
    const TONESCALE_CSV: &str =
        include_str!("../../reference-checks/golden/aces2_ocio_tonescale_compress.csv");
    const GAMUT_CSV: &str =
        include_str!("../../reference-checks/golden/aces2_ocio_gamut_compress.csv");
    const OT_CSV: &str =
        include_str!("../../reference-checks/golden/aces2_ocio_output_transform.csv");
    const OT_INV_CSV: &str =
        include_str!("../../reference-checks/golden/aces2_ocio_output_transform_inv.csv");

    fn rows(csv: &str) -> Vec<Vec<&str>> {
        csv.lines()
            .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
            .map(|l| l.split(',').collect())
            .collect()
    }

    fn f(s: &str) -> f32 {
        s.trim()
            .parse()
            .unwrap_or_else(|_| panic!("bad float {s:?}"))
    }

    fn prims(name: &str) -> Chromaticities {
        match name {
            "ap0" => Chromaticities::AP0,
            "ap1" => Chromaticities::AP1,
            "rec709" => Chromaticities::REC709,
            "p3d65" => Chromaticities::P3_D65,
            "rec2020" => Chromaticities::REC2020,
            other => panic!("unknown primaries {other}"),
        }
    }

    /// Hue is compared circularly and only when M is large enough for the
    /// angle to be numerically meaningful.
    fn assert_jmh_close(
        got: [f32; 3],
        want: [f32; 3],
        tol_j: f32,
        tol_m: f32,
        tol_h: f32,
        ctx: &str,
    ) {
        assert_jmh_close_rel(got, want, tol_j, tol_m, 1e-4, tol_h, ctx);
    }

    fn assert_jmh_close_rel(
        got: [f32; 3],
        want: [f32; 3],
        tol_j: f32,
        tol_m: f32,
        rel_m: f32,
        tol_h: f32,
        ctx: &str,
    ) {
        assert!(
            (got[0] - want[0]).abs() <= tol_j,
            "{ctx}: J {} vs {} (tol {tol_j})",
            got[0],
            want[0]
        );
        let m_tol = tol_m + want[1].abs() * rel_m;
        assert!(
            (got[1] - want[1]).abs() <= m_tol,
            "{ctx}: M {} vs {} (tol {m_tol})",
            got[1],
            want[1]
        );
        if want[1] > 0.05 {
            let mut dh = (got[2] - want[2]).abs();
            if dh > 180.0 {
                dh = 360.0 - dh;
            }
            assert!(
                dh <= tol_h,
                "{ctx}: h {} vs {} (tol {tol_h})",
                got[2],
                want[2]
            );
        }
    }

    #[test]
    fn rgb_to_jmh_matches_ocio() {
        let mut checked = 0;
        for r in rows(JMH_CSV) {
            let p = JmhParams::new(&prims(r[0])).unwrap();
            let rgb = [f(r[1]), f(r[2]), f(r[3])];
            let want = [f(r[4]), f(r[5]), f(r[6])];
            let got = p.rgb_to_jmh(rgb);
            assert_jmh_close(
                got,
                want,
                2e-3,
                2e-3,
                1e-2,
                &alloc::format!("{} {rgb:?}", r[0]),
            );
            // And back: the CAM must invert to the input RGB.
            if got[0] > 0.0 {
                let back = p.jmh_to_rgb(got);
                for c in 0..3 {
                    let tol = 1e-4 + rgb[c].abs() * 2e-4;
                    assert!(
                        (back[c] - rgb[c]).abs() <= tol,
                        "{} {rgb:?}: JMh round trip {back:?}",
                        r[0]
                    );
                }
            }
            checked += 1;
        }
        assert!(checked >= 200, "only {checked} rows");
    }

    #[test]
    fn tonescale_and_chroma_compress_match_ocio() {
        let mut ots: Vec<(f32, Aces2OutputTransform)> = Vec::new();
        let mut checked = 0;
        for r in rows(TONESCALE_CSV) {
            let peak = f(r[0]);
            if ots.iter().all(|(p, _)| *p != peak) {
                let cfg = Aces2Config {
                    peak_luminance: peak,
                    limiting_primaries: Chromaticities::REC709,
                };
                ots.push((peak, Aces2OutputTransform::new(cfg).unwrap()));
            }
            let ot = &ots.iter().find(|(p, _)| *p == peak).unwrap().1;
            let jmh = [f(r[1]), f(r[2]), f(r[3])];
            let want = [f(r[4]), f(r[5]), f(r[6])];
            let got = ot.tonemap_and_compress_fwd(jmh);
            assert_jmh_close(
                got,
                want,
                2e-3,
                2e-3,
                1e-2,
                &alloc::format!("peak {peak} {jmh:?}"),
            );
            // Inverse of the forward must recover the input JMh (the toe
            // inversion loses a few f32 ULPs at extreme M, hence 5e-4 rel).
            if jmh[0] > 0.0 {
                let back = ot.tonemap_and_compress_inv(got);
                assert_jmh_close_rel(
                    back,
                    jmh,
                    5e-3,
                    5e-3,
                    5e-4,
                    1e-2,
                    &alloc::format!("peak {peak} inv {jmh:?}"),
                );
            }
            checked += 1;
        }
        assert!(checked >= 150, "only {checked} rows");
    }

    #[test]
    fn gamut_compress_matches_ocio() {
        let mut ots: Vec<(f32, &str, Aces2OutputTransform)> = Vec::new();
        let mut checked = 0;
        for r in rows(GAMUT_CSV) {
            let peak = f(r[0]);
            let name = r[1];
            if ots.iter().all(|(p, n, _)| !(*p == peak && *n == name)) {
                let cfg = Aces2Config {
                    peak_luminance: peak,
                    limiting_primaries: prims(name),
                };
                ots.push((peak, name, Aces2OutputTransform::new(cfg).unwrap()));
            }
            let ot = &ots
                .iter()
                .find(|(p, n, _)| *p == peak && *n == name)
                .unwrap()
                .2;
            let jmh = [f(r[2]), f(r[3]), f(r[4])];
            let want = [f(r[5]), f(r[6]), f(r[7])];
            let got = ot.gamut_compress_fwd(jmh);
            assert_jmh_close(
                got,
                want,
                5e-3,
                5e-3,
                1e-2,
                &alloc::format!("peak {peak} {name} {jmh:?}"),
            );
            checked += 1;
        }
        assert!(checked >= 150, "only {checked} rows");
    }

    #[test]
    fn output_transform_matches_ocio() {
        let mut ots: Vec<(f32, &str, Aces2OutputTransform)> = Vec::new();
        let mut checked = 0;
        let mut in_ap1 = 0;
        for r in rows(OT_CSV) {
            let peak = f(r[0]);
            let name = r[1];
            if ots.iter().all(|(p, n, _)| !(*p == peak && *n == name)) {
                let cfg = Aces2Config {
                    peak_luminance: peak,
                    limiting_primaries: prims(name),
                };
                ots.push((peak, name, Aces2OutputTransform::new(cfg).unwrap()));
            }
            let ot = &ots
                .iter()
                .find(|(p, n, _)| *p == peak && *n == name)
                .unwrap()
                .2;
            let rgb = [f(r[2]), f(r[3]), f(r[4])];
            let want = [f(r[5]), f(r[6]), f(r[7])];
            // OpenColorIO's fixed function omits the CTL's AP1 clamp, so the
            // golden is held against the unclamped rendering; `forward` must
            // agree wherever the clamp is a no-op.
            let got = ot.forward_unclamped(rgb);
            for c in 0..3 {
                let tol = 1e-3 + want[c].abs() * 1e-3;
                assert!(
                    (got[c] - want[c]).abs() <= tol,
                    "peak {peak} {name} {rgb:?}: out {got:?} vs {want:?}"
                );
            }
            let clamped = ot.clamp_ap0_to_ap1(rgb);
            if (0..3).all(|c| (clamped[c] - rgb[c]).abs() <= 1e-6 + rgb[c].abs() * 1e-6) {
                // The clamp's AP0→AP1→AP0 matrix round trip perturbs the
                // input by a few ULPs, so compare with a tolerance.
                let via_forward = ot.forward(rgb);
                for c in 0..3 {
                    assert!(
                        (via_forward[c] - got[c]).abs() <= 1e-6 + got[c].abs() * 1e-5,
                        "peak {peak} {name} {rgb:?}: clamp changed an in-AP1 input: {via_forward:?} vs {got:?}"
                    );
                }
                in_ap1 += 1;
            }
            checked += 1;
        }
        assert!(checked >= 280, "only {checked} rows compared");
        assert!(
            in_ap1 >= 150 && in_ap1 < checked,
            "{in_ap1} of {checked} rows inside AP1"
        );
    }

    #[test]
    fn inverse_output_transform_matches_ocio() {
        let mut ots: Vec<(f32, &str, Aces2OutputTransform)> = Vec::new();
        let mut checked = 0;
        for r in rows(OT_INV_CSV) {
            let peak = f(r[0]);
            let name = r[1];
            if ots.iter().all(|(p, n, _)| !(*p == peak && *n == name)) {
                let cfg = Aces2Config {
                    peak_luminance: peak,
                    limiting_primaries: prims(name),
                };
                ots.push((peak, name, Aces2OutputTransform::new(cfg).unwrap()));
            }
            let ot = &ots
                .iter()
                .find(|(p, n, _)| *p == peak && *n == name)
                .unwrap()
                .2;
            let display = [f(r[2]), f(r[3]), f(r[4])];
            let want = [f(r[5]), f(r[6]), f(r[7])];
            let got = ot.inverse(display);
            // Error relative to the pixel's magnitude (largest channel, with
            // a 1e-3 floor). The inverse is ill-conditioned wherever the
            // forward saturated — display values at the peak or a channel
            // pinned near zero by the AP1 fold, or a near-black display value
            // whose scene value is tens of thousands of times larger — and
            // there this port and OpenColorIO agree to ~1e-2 of the pixel
            // magnitude; everywhere else to ~1e-4.
            let scale = want.iter().fold(1e-3f32, |m, v| m.max(v.abs()));
            for c in 0..3 {
                assert!(
                    (got[c] - want[c]).abs() <= 2e-2 * scale,
                    "peak {peak} {name} display {display:?}: inverse {got:?} vs {want:?}"
                );
            }
            checked += 1;
        }
        assert!(checked >= 280, "only {checked} rows compared");
    }

    #[test]
    fn forward_inverse_round_trip() {
        let ot = Aces2OutputTransform::new(Aces2Config::default()).unwrap();
        let samples = [
            [0.18, 0.18, 0.18],
            [0.5, 0.2, 0.05],
            [0.02, 0.3, 0.1],
            [1.0, 1.0, 1.0],
            [0.1, 0.1, 0.4],
        ];
        for rgb in samples {
            // The inverse recovers the *clamped* input: AP0 colours outside
            // the AP1 cube are folded onto it before rendering.
            let expect = ot.clamp_ap0_to_ap1(rgb);
            let disp = ot.forward(rgb);
            let back = ot.inverse(disp);
            for c in 0..3 {
                assert!(
                    (back[c] - expect[c]).abs() <= 2e-3 + expect[c].abs() * 1e-2,
                    "{rgb:?} -> {disp:?} -> {back:?} (expected {expect:?})"
                );
            }
        }
    }

    #[test]
    fn endpoints_and_robustness() {
        let sdr = Aces2OutputTransform::new(Aces2Config::default()).unwrap();
        // Black stays black; 18% grey lands near the 10.013 cd/m² anchor.
        assert_eq!(sdr.forward([0.0; 3]), [0.0; 3]);
        let grey = sdr.forward([0.18; 3]);
        assert!((grey[0] - 0.10013).abs() < 2e-3, "{grey:?}");
        // Very bright neutral saturates at the display peak (1.0 = 100 nits).
        let white = sdr.forward([100.0; 3]);
        assert!(white.iter().all(|&c| (c - 1.0).abs() < 5e-3), "{white:?}");
        // A 1000-nit target reaches 10.0.
        let hdr = Aces2OutputTransform::new(Aces2Config {
            peak_luminance: 1000.0,
            limiting_primaries: Chromaticities::REC2020,
        })
        .unwrap();
        // The tonescale hits exactly `n` at scene value `r_hit` and overshoots
        // by a few percent up to the `forward_limit` clamp (the CTL relies on
        // the display encoding to clip), so allow +1%.
        let w = hdr.forward([1000.0; 3]);
        assert!(w.iter().all(|&c| (9.95..=10.1).contains(&c)), "{w:?}");
        // Hostile input: finite output, inside the display cube.
        for rgb in [
            [f32::NAN, 0.5, 0.5],
            [f32::INFINITY, 0.0, 0.0],
            [-1.0e30, 1.0e30, 0.0],
            [f32::MAX, f32::MIN, 0.0],
            [-0.5, -0.5, -0.5],
        ] {
            let out = sdr.forward(rgb);
            assert!(
                out.iter()
                    .all(|&c| c.is_finite() && (-1e-3..=1.01).contains(&c)),
                "{rgb:?} -> {out:?}"
            );
        }
        // Trait dispatch is the forward transform.
        let via_trait = ToneMap::map_rgb(&sdr, [0.3, 0.2, 0.1]);
        assert_eq!(via_trait, sdr.forward([0.3, 0.2, 0.1]));
    }

    #[test]
    fn rejects_bad_config() {
        for peak in [0.0, 0.5, -100.0, f32::NAN, f32::INFINITY] {
            let cfg = Aces2Config {
                peak_luminance: peak,
                limiting_primaries: Chromaticities::REC709,
            };
            assert!(Aces2OutputTransform::new(cfg).is_err(), "peak {peak}");
        }
        let degenerate = Chromaticities {
            red: [0.3, 0.3],
            green: [0.3, 0.3],
            blue: [0.3, 0.3],
            white: [0.3127, 0.3290],
        };
        let cfg = Aces2Config {
            peak_luminance: 100.0,
            limiting_primaries: degenerate,
        };
        assert!(Aces2OutputTransform::new(cfg).is_err());
    }
}
