//! ACES 2.0 display encoding — the wrapper the ACES output presets put
//! around the rendering ([`Aces2OutputTransform`]).
//!
//! A port of `Lib.Academy.DisplayEncoding.ctl` plus the `main()` of the
//! preset files in <https://github.com/aces-aswf/aces-output> (`main` as of
//! 2025-10). For a forward preset the CTL does:
//!
//! ```text
//! ACES2065-1 ─ outputTransform_fwd (Aces2OutputTransform::forward)
//!   → clamp to [0, peak_luminance / 100]
//!   → white scaling (only when the limiting white ≠ the encoding white)
//!   → limiting primaries → encoding primaries (plain matrix, no adaptation)
//!   → × linear_scale (48 / 52.37 for DCDM, else 1)
//!   → inverse EOTF (sRGB, gamma 2.2 / 2.6, BT.1886, ST 2084, HLG, or none)
//! ```
//!
//! and the inverse preset runs the same steps backwards. The inverse
//! white-scale step in the CTL clamps to `[0, 1]`; this port clamps to
//! `[0, peak_luminance / 100]` (identical for SDR presets, and what the
//! next step clamps to anyway) so HDR "D60 sim" presets invert above 100
//! cd/m² — the behaviour OpenColorIO's builtins have.
//!
//! **Parity.** Held to OpenColorIO 2.5's `ACES-OUTPUT - … _2.0` builtins
//! composed with its `DISPLAY - CIE-XYZ-D65_to_…` builtins on
//! `reference-checks/golden/aces2_ocio_display_encoding{,_inv}.csv`
//! (generated by `reference-checks/aces_ocio_encodings_reference.py`).

use alloc::format;
use alloc::string::String;

use super::aces2::{
    Aces2Config, Aces2OutputTransform, Chromaticities, Mat3, invert, mul_mm, mul_vm,
    rgb_to_xyz_matrix, xyz_to_rgb_matrix,
};
use crate::{Error, Result, ToneMap};
use libm::{expf, logf, powf, sqrtf};

/// `ref_luminance` in the CTL: display-linear `1.0` is 100 cd/m².
const REF_LUMINANCE: f32 = 100.0;

// SMPTE ST 2084 constants.
const PQ_M1: f32 = 0.1593017578125;
const PQ_M2: f32 = 78.84375;
const PQ_C1: f32 = 0.8359375;
const PQ_C2: f32 = 18.8515625;
const PQ_C3: f32 = 18.6875;
const PQ_C: f32 = 10000.0;

// ITU-R BT.2100 HLG constants.
const HLG_A: f32 = 0.17883277;
const HLG_B: f32 = 0.28466892;
const HLG_C: f32 = 0.55991073;

/// `linear_scale_factor` of the DCDM (X'Y'Z') presets: 48 cd/m² peak
/// expressed against the 52.37 cd/m² the 2.6-gamma encoding reaches.
pub const DCDM_LINEAR_SCALE: f32 = 48.0 / 52.37;

/// Display EOTF an ACES 2.0 preset encodes for (`eotf_enum` in the CTL).
///
/// [`encode`](Self::encode) is the *inverse* EOTF (display-linear → code
/// value); [`decode`](Self::decode) is the EOTF. Display-linear `1.0` is
/// 100 cd/m² for the absolute encodings (ST 2084, HLG) and the display peak
/// for the relative ones.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum DisplayEotf {
    /// No encoding: code value = display-linear.
    Linear,
    /// SMPTE ST 2084 (PQ), absolute: `1.0` display-linear = 100 cd/m².
    St2084,
    /// ITU-R BT.2100 HLG, via the BT.2390 §7 PQ→HLG conversion at 1000
    /// cd/m² nominal peak (as the CTL does it).
    Hlg,
    /// Pure power 2.6 (DCDM / cinema).
    Gamma26,
    /// ITU-R BT.1886 with γ = 2.4, `Lw = 1`, `Lb = 0` (a pure power 2.4).
    Bt1886,
    /// Pure power 2.2.
    Gamma22,
    /// IEC 61966-2-1:1999 sRGB piecewise curve.
    SrgbPiecewise,
}

impl DisplayEotf {
    /// Inverse EOTF: display-linear → code value (`eotf_inv` in the CTL).
    /// Negative input clamps to `0` first, as the CTL does.
    #[must_use]
    pub fn encode(self, linear: f32) -> f32 {
        let v = linear.max(0.0);
        match self {
            Self::Linear => v,
            Self::St2084 => y_to_st2084(v * REF_LUMINANCE),
            Self::Hlg => st2084_to_hlg_1000nits(y_to_st2084(v * REF_LUMINANCE)),
            Self::Gamma26 => powf(v, 1.0 / 2.6),
            Self::Bt1886 => bt1886_inv(v, 2.4),
            Self::Gamma22 => powf(v, 1.0 / 2.2),
            Self::SrgbPiecewise => moncurve_inv(v, 2.4, 0.055),
        }
    }

    /// EOTF: code value → display-linear (`eotf` in the CTL).
    #[must_use]
    pub fn decode(self, code_value: f32) -> f32 {
        match self {
            Self::Linear => code_value,
            Self::St2084 => st2084_to_y(code_value) / REF_LUMINANCE,
            Self::Hlg => st2084_to_y(hlg_to_st2084_1000nits(code_value)) / REF_LUMINANCE,
            Self::Gamma26 => powf(code_value, 2.6),
            Self::Bt1886 => bt1886_fwd(code_value, 2.4),
            Self::Gamma22 => powf(code_value, 2.2),
            Self::SrgbPiecewise => moncurve_fwd(code_value, 2.4, 0.055),
        }
    }

    /// Encode all three channels.
    #[must_use]
    pub fn encode_rgb(self, rgb: [f32; 3]) -> [f32; 3] {
        [
            self.encode(rgb[0]),
            self.encode(rgb[1]),
            self.encode(rgb[2]),
        ]
    }

    /// Decode all three channels.
    #[must_use]
    pub fn decode_rgb(self, cv: [f32; 3]) -> [f32; 3] {
        [self.decode(cv[0]), self.decode(cv[1]), self.decode(cv[2])]
    }

    /// The EOTF's token in an ACES transform ID (`None` for `Linear`,
    /// which no shipped preset uses).
    fn transform_id_token(self) -> Option<&'static str> {
        Some(match self {
            Self::Linear => return None,
            Self::St2084 => "ST2084",
            Self::Hlg => "HLG",
            Self::Gamma26 => "Gamma2pt6",
            Self::Bt1886 => "BT1886",
            Self::Gamma22 => "Gamma2pt2",
            Self::SrgbPiecewise => "sRGB-Piecewise",
        })
    }
}

// -- transfer functions (Lib.Academy.DisplayEncoding.ctl) -------------------

/// `moncurve_fwd`: code value → linear, γ = 2.4 / offset 0.055 is sRGB.
fn moncurve_fwd(x: f32, gamma: f32, offs: f32) -> f32 {
    let fs = ((gamma - 1.0) / offs) * powf(offs * gamma / ((gamma - 1.0) * (1.0 + offs)), gamma);
    let xb = offs / (gamma - 1.0);
    if x >= xb {
        powf((x + offs) / (1.0 + offs), gamma)
    } else {
        x * fs
    }
}

/// `moncurve_inv`: linear → code value.
fn moncurve_inv(y: f32, gamma: f32, offs: f32) -> f32 {
    let yb = powf(offs * gamma / ((gamma - 1.0) * (1.0 + offs)), gamma);
    let rs = powf((gamma - 1.0) / offs, gamma - 1.0) * powf((1.0 + offs) / gamma, gamma);
    if y >= yb {
        (1.0 + offs) * powf(y, 1.0 / gamma) - offs
    } else {
        y * rs
    }
}

/// `bt1886_fwd` with `Lw = 1`, `Lb = 0`: `L = max(V, 0)^γ`.
fn bt1886_fwd(v: f32, gamma: f32) -> f32 {
    powf(v.max(0.0), gamma)
}

/// `bt1886_inv` with `Lw = 1`, `Lb = 0`: `V = max(L, 0)^(1/γ)`.
fn bt1886_inv(l: f32, gamma: f32) -> f32 {
    powf(l.max(0.0), 1.0 / gamma)
}

/// `ST2084_to_Y`: PQ code value (full range) → cd/m².
fn st2084_to_y(n: f32) -> f32 {
    let np = powf(n, 1.0 / PQ_M2);
    let l = (np - PQ_C1).max(0.0) / (PQ_C2 - PQ_C3 * np);
    powf(l, 1.0 / PQ_M1) * PQ_C
}

/// `Y_to_ST2084`: cd/m² → PQ code value (full range).
fn y_to_st2084(c: f32) -> f32 {
    let lm = powf(c / PQ_C, PQ_M1);
    powf((PQ_C1 + PQ_C2 * lm) / (1.0 + PQ_C3 * lm), PQ_M2)
}

/// `ST2084_to_HLG_1000nits`, per channel. The CTL computes the inverse OOTF
/// from the pixel's BT.2020 luminance, so this takes the whole triple.
fn st2084_to_hlg_1000nits_rgb(pq: [f32; 3]) -> [f32; 3] {
    let display = [st2084_to_y(pq[0]), st2084_to_y(pq[1]), st2084_to_y(pq[2])];
    let y_d = 0.2627 * display[0] + 0.6780 * display[1] + 0.0593 * display[2];
    const L_W: f32 = 1000.0;
    const GAMMA: f32 = 1.2;
    let mut scene = [0.0f32; 3];
    if y_d != 0.0 {
        let k = powf(y_d / L_W, (1.0 - GAMMA) / GAMMA);
        for c in 0..3 {
            scene[c] = k * (display[c] / L_W);
        }
    }
    [hlg_oetf(scene[0]), hlg_oetf(scene[1]), hlg_oetf(scene[2])]
}

/// Scalar convenience used by [`DisplayEotf::encode`]: for a single channel
/// the inverse OOTF's luminance is the channel itself scaled by its BT.2020
/// weight — which is *not* what the CTL does per pixel. Per-pixel encoding
/// goes through [`st2084_to_hlg_1000nits_rgb`]; this scalar form is only
/// exact for neutral pixels and exists so the enum has a per-channel API.
fn st2084_to_hlg_1000nits(pq: f32) -> f32 {
    st2084_to_hlg_1000nits_rgb([pq; 3])[0]
}

/// `HLG_to_ST2084_1000nits`, whole triple (OOTF needs the luminance).
fn hlg_to_st2084_1000nits_rgb(hlg: [f32; 3]) -> [f32; 3] {
    let scene = [hlg_eotf(hlg[0]), hlg_eotf(hlg[1]), hlg_eotf(hlg[2])];
    let y_s = 0.2627 * scene[0] + 0.6780 * scene[1] + 0.0593 * scene[2];
    const L_W: f32 = 1000.0;
    const GAMMA: f32 = 1.2;
    let k = L_W * powf(y_s, GAMMA - 1.0);
    [
        y_to_st2084(k * scene[0]),
        y_to_st2084(k * scene[1]),
        y_to_st2084(k * scene[2]),
    ]
}

fn hlg_to_st2084_1000nits(hlg: f32) -> f32 {
    hlg_to_st2084_1000nits_rgb([hlg; 3])[0]
}

/// HLG OETF: scene-linear (`1/12` = nominal peak) → signal.
fn hlg_oetf(x: f32) -> f32 {
    if x <= 1.0 / 12.0 {
        sqrtf(3.0 * x)
    } else {
        HLG_A * logf(12.0 * x - HLG_B) + HLG_C
    }
}

/// HLG inverse OETF: signal → scene-linear.
fn hlg_eotf(v: f32) -> f32 {
    if (0.0..=0.5).contains(&v) {
        v * v / 3.0
    } else {
        (expf((v - HLG_C) / HLG_A) + HLG_B) / 12.0
    }
}

// -- the preset wrapper -----------------------------------------------------

/// How an ACES 2.0 preset encodes the rendered image for a display: the
/// encoding primaries, EOTF, and the two switches the preset files carry.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Aces2DisplayEncoding {
    /// Primaries and white the code values are expressed in
    /// (`encodingPri` in the presets). Usually equals the limiting
    /// primaries; the "D60 sim" presets limit to a D60 gamut but encode in
    /// the display's D65 one, and DCDM encodes in [`Chromaticities::XYZ_E`].
    pub encoding_primaries: Chromaticities,
    /// Inverse EOTF applied last.
    pub eotf: DisplayEotf,
    /// `scale_white`: when the limiting white differs from the encoding
    /// white, scale so the largest channel of the creative white hits `1.0`
    /// instead of clipping (the presets set this iff the whites differ).
    pub scale_white: bool,
    /// `linear_scale_factor`: multiplied into display-linear before the
    /// inverse EOTF. `1.0` for every preset except DCDM
    /// ([`DCDM_LINEAR_SCALE`]).
    pub linear_scale: f32,
}

impl Aces2DisplayEncoding {
    /// sRGB piecewise, Rec.709 primaries, D65 — the `sRGB-Piecewise` presets.
    pub const SRGB: Self = Self {
        encoding_primaries: Chromaticities::REC709,
        eotf: DisplayEotf::SrgbPiecewise,
        scale_white: false,
        linear_scale: 1.0,
    };
    /// Gamma 2.2, Rec.709 primaries, D65 — the `Gamma2pt2` presets.
    pub const REC709_GAMMA22: Self = Self {
        eotf: DisplayEotf::Gamma22,
        ..Self::SRGB
    };
    /// BT.1886, Rec.709 primaries, D65 — the `BT1886` presets.
    pub const REC709_BT1886: Self = Self {
        eotf: DisplayEotf::Bt1886,
        ..Self::SRGB
    };
    /// sRGB piecewise in P3-D65 (Display P3).
    pub const DISPLAY_P3: Self = Self {
        encoding_primaries: Chromaticities::P3_D65,
        ..Self::SRGB
    };
    /// Gamma 2.6 in P3-D65 — the P3 48-nit cinema presets.
    pub const P3_D65_GAMMA26: Self = Self {
        encoding_primaries: Chromaticities::P3_D65,
        eotf: DisplayEotf::Gamma26,
        ..Self::SRGB
    };
    /// ST 2084 (PQ) in P3-D65.
    pub const P3_D65_ST2084: Self = Self {
        encoding_primaries: Chromaticities::P3_D65,
        eotf: DisplayEotf::St2084,
        ..Self::SRGB
    };
    /// ST 2084 (PQ) in Rec.2100 — HDR10-style output.
    pub const REC2100_ST2084: Self = Self {
        encoding_primaries: Chromaticities::REC2020,
        eotf: DisplayEotf::St2084,
        ..Self::SRGB
    };
    /// HLG in Rec.2100.
    pub const REC2100_HLG: Self = Self {
        encoding_primaries: Chromaticities::REC2020,
        eotf: DisplayEotf::Hlg,
        ..Self::SRGB
    };
    /// DCDM X'Y'Z' (gamma 2.6, equal-energy white, 48 / 52.37 scale).
    pub const DCDM_GAMMA26: Self = Self {
        encoding_primaries: Chromaticities::XYZ_E,
        eotf: DisplayEotf::Gamma26,
        scale_white: false,
        linear_scale: DCDM_LINEAR_SCALE,
    };
    /// DCDM X'Y'Z' with ST 2084 (the 300-nit cinema HDR preset).
    pub const DCDM_ST2084: Self = Self {
        eotf: DisplayEotf::St2084,
        ..Self::DCDM_GAMMA26
    };

    /// This encoding with `scale_white` set — what the "D60 sim" presets
    /// (a D60 limiting gamut encoded in a D65 display) use.
    #[must_use]
    pub const fn with_white_scaling(self) -> Self {
        Self {
            scale_white: true,
            ..self
        }
    }
}

impl Default for Aces2DisplayEncoding {
    /// [`Self::SRGB`].
    fn default() -> Self {
        Self::SRGB
    }
}

/// An ACES 2.0 output preset: the rendering ([`Aces2OutputTransform`]) plus
/// the display encoding, ACES2065-1 in and display code values out — the
/// whole of an `Output.Academy.*` CTL file.
///
/// Implements [`ToneMap`] with `map_rgb` = [`forward`](Self::forward), so
/// the output is *encoded* (non-linear) code values, unlike every other
/// zentone tonemapper. Use [`Aces2OutputTransform`] directly for
/// display-linear output.
#[derive(Debug, Clone)]
pub struct Aces2DisplayTransform {
    ot: Aces2OutputTransform,
    config: Aces2Config,
    encoding: Aces2DisplayEncoding,
    limit_to_display: Mat3,
    display_to_limit: Mat3,
    /// `1 / largest channel of the limiting white in the encoding primaries`
    /// when `scale_white`, else `1`.
    white_scale: f32,
    clamp_max: f32,
}

impl Aces2DisplayTransform {
    /// Build the rendering for `config` and wrap it in `encoding`.
    ///
    /// # Errors
    ///
    /// Everything [`Aces2OutputTransform::new`] rejects, plus
    /// `Error::InvalidConfig` for degenerate encoding primaries or a
    /// non-positive / non-finite `linear_scale`.
    pub fn new(config: Aces2Config, encoding: Aces2DisplayEncoding) -> Result<Self> {
        Self::from_output_transform(Aces2OutputTransform::new(config)?, config, encoding)
    }

    /// Wrap an already-built rendering. `config` must be the one `ot` was
    /// built from (it is not re-derived; it feeds the transform ID and the
    /// peak clamp).
    ///
    /// # Errors
    ///
    /// `Error::InvalidConfig` if `config.peak_luminance` disagrees with
    /// `ot`, the encoding primaries are degenerate, or `linear_scale` is
    /// not a positive finite number.
    pub fn from_output_transform(
        ot: Aces2OutputTransform,
        config: Aces2Config,
        encoding: Aces2DisplayEncoding,
    ) -> Result<Self> {
        if ot.peak_luminance() != config.peak_luminance {
            return Err(Error::InvalidConfig(
                "ACES 2.0 display: config.peak_luminance does not match the output transform",
            ));
        }
        if !(encoding.linear_scale.is_finite() && encoding.linear_scale > 0.0) {
            return Err(Error::InvalidConfig(
                "ACES 2.0 display: linear_scale must be finite and > 0",
            ));
        }
        let bad = || Error::InvalidConfig("ACES 2.0 display: encoding primaries are degenerate");
        let limit_to_display = mul_mm(
            &rgb_to_xyz_matrix(&config.limiting_primaries, 1.0),
            &xyz_to_rgb_matrix(&encoding.encoding_primaries, 1.0).ok_or_else(bad)?,
        );
        let display_to_limit = invert(&limit_to_display).ok_or_else(bad)?;
        let white_scale = if encoding.scale_white {
            let w = mul_vm([1.0; 3], &limit_to_display);
            let largest = w[0].max(w[1]).max(w[2]);
            if !(largest.is_finite() && largest > 0.0) {
                return Err(bad());
            }
            1.0 / largest
        } else {
            1.0
        };
        Ok(Self {
            ot,
            config,
            encoding,
            limit_to_display,
            display_to_limit,
            white_scale,
            clamp_max: config.peak_luminance / REF_LUMINANCE,
        })
    }

    /// The wrapped rendering.
    #[must_use]
    pub fn output_transform(&self) -> &Aces2OutputTransform {
        &self.ot
    }

    /// The rendering configuration.
    #[must_use]
    pub fn config(&self) -> &Aces2Config {
        &self.config
    }

    /// The display encoding.
    #[must_use]
    pub fn encoding(&self) -> &Aces2DisplayEncoding {
        &self.encoding
    }

    /// Full preset: ACES2065-1 → display code values.
    #[must_use]
    pub fn forward(&self, aces: [f32; 3]) -> [f32; 3] {
        self.encode_display(self.ot.forward(aces))
    }

    /// Full inverse preset: display code values → ACES2065-1.
    #[must_use]
    pub fn inverse(&self, code_values: [f32; 3]) -> [f32; 3] {
        self.ot.inverse(self.decode_display(code_values))
    }

    /// The encoding half alone: display-linear RGB in the limiting
    /// primaries (what [`Aces2OutputTransform::forward`] returns) → code
    /// values. Peak clamp, white scaling, primaries matrix, linear scale,
    /// inverse EOTF.
    #[must_use]
    pub fn encode_display(&self, rgb_limit: [f32; 3]) -> [f32; 3] {
        let mut rgb = [
            clamp_nan_to_zero(rgb_limit[0], self.clamp_max),
            clamp_nan_to_zero(rgb_limit[1], self.clamp_max),
            clamp_nan_to_zero(rgb_limit[2], self.clamp_max),
        ];
        if self.encoding.scale_white {
            for c in &mut rgb {
                *c *= self.white_scale;
            }
        }
        let display = mul_vm(rgb, &self.limit_to_display);
        let s = self.encoding.linear_scale;
        let scaled = [
            (display[0] * s).max(0.0),
            (display[1] * s).max(0.0),
            (display[2] * s).max(0.0),
        ];
        match self.encoding.eotf {
            // HLG's inverse OOTF is a per-pixel (luminance) operation.
            DisplayEotf::Hlg => st2084_to_hlg_1000nits_rgb([
                y_to_st2084(scaled[0] * REF_LUMINANCE),
                y_to_st2084(scaled[1] * REF_LUMINANCE),
                y_to_st2084(scaled[2] * REF_LUMINANCE),
            ]),
            eotf => eotf.encode_rgb(scaled),
        }
    }

    /// The decoding half alone: code values → display-linear RGB in the
    /// limiting primaries, clamped to `[0, peak_luminance / 100]` (what
    /// [`Aces2OutputTransform::inverse`] expects).
    #[must_use]
    pub fn decode_display(&self, code_values: [f32; 3]) -> [f32; 3] {
        let display = match self.encoding.eotf {
            DisplayEotf::Hlg => {
                let pq = hlg_to_st2084_1000nits_rgb(code_values);
                [
                    st2084_to_y(pq[0]) / REF_LUMINANCE,
                    st2084_to_y(pq[1]) / REF_LUMINANCE,
                    st2084_to_y(pq[2]) / REF_LUMINANCE,
                ]
            }
            eotf => eotf.decode_rgb(code_values),
        };
        let inv_s = 1.0 / self.encoding.linear_scale;
        let mut rgb = mul_vm(
            [display[0] * inv_s, display[1] * inv_s, display[2] * inv_s],
            &self.display_to_limit,
        );
        if self.encoding.scale_white {
            let inv = 1.0 / self.white_scale;
            for c in &mut rgb {
                *c *= inv;
            }
        }
        [
            clamp_nan_to_zero(rgb[0], self.clamp_max),
            clamp_nan_to_zero(rgb[1], self.clamp_max),
            clamp_nan_to_zero(rgb[2], self.clamp_max),
        ]
    }

    /// The `ACEStransformID` of the matching `Output.Academy.*` preset in
    /// <https://github.com/aces-aswf/aces-output>, e.g.
    /// `urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_100nit_in_Rec709-D65_sRGB-Piecewise.a2.v1`,
    /// or `None` when this configuration is not one of the 54 shipped
    /// presets (unknown primaries, an unlisted peak, `Linear`, or
    /// `scale_white` / `linear_scale` set differently from the preset).
    #[must_use]
    pub fn transform_id(&self) -> Option<&'static str> {
        let name = self.preset_name()?;
        ACES_OUTPUT_TRANSFORM_IDS.iter().copied().find(|id| {
            id.strip_prefix(TRANSFORM_ID_PREFIX)
                .and_then(|s| s.strip_suffix(".a2.v1"))
                == Some(name.as_str())
        })
    }

    /// `<Limit>_<nit>nit_in_<Encoding>_<EOTF>` for the preset naming scheme.
    fn preset_name(&self) -> Option<String> {
        let c = self.config;
        let e = self.encoding;
        let limit = if c.limiting_primaries == Chromaticities::REC709 {
            "Rec709-D65"
        } else if c.limiting_primaries == Chromaticities::REC709_D60 {
            "Rec709-D60"
        } else if c.limiting_primaries == Chromaticities::P3_D65 {
            "P3-D65"
        } else if c.limiting_primaries == Chromaticities::P3_D60 {
            "P3-D60"
        } else if c.limiting_primaries == Chromaticities::REC2020 {
            "Rec2100-D65"
        } else if c.limiting_primaries == Chromaticities::REC2020_D60 {
            "Rec2100-D60"
        } else {
            return None;
        };
        let (encoding, dcdm) = if e.encoding_primaries == Chromaticities::REC709 {
            ("Rec709-D65", false)
        } else if e.encoding_primaries == Chromaticities::P3_D65 {
            ("P3-D65", false)
        } else if e.encoding_primaries == Chromaticities::REC2020 {
            ("Rec2100-D65", false)
        } else if e.encoding_primaries == Chromaticities::XYZ_E {
            ("XYZ-E", true)
        } else {
            return None;
        };
        let whites_differ = c.limiting_primaries.white != e.encoding_primaries.white;
        if e.scale_white != (whites_differ && !dcdm) {
            return None;
        }
        let expected_scale = if dcdm { DCDM_LINEAR_SCALE } else { 1.0 };
        if (e.linear_scale - expected_scale).abs() > 1e-6 {
            return None;
        }
        // DCDM presets are named by the projector peak (48 / 300 cd/m²) while
        // the tonescale targets that × 100/48.
        let nits = if dcdm {
            c.peak_luminance * 0.48
        } else {
            c.peak_luminance
        };
        if !(nits.is_finite() && nits >= 1.0 && (nits - libm::roundf(nits)).abs() < 1e-3) {
            return None;
        }
        let eotf = e.eotf.transform_id_token()?;
        Some(format!(
            "Output.Academy.{limit}_{}nit_in_{encoding}_{eotf}",
            libm::roundf(nits) as u32
        ))
    }
}

impl ToneMap for Aces2DisplayTransform {
    /// [`forward`](Self::forward): ACES2065-1 in, display **code values**
    /// (encoded, not linear) out.
    #[inline]
    fn map_rgb(&self, rgb: [f32; 3]) -> [f32; 3] {
        self.forward(rgb)
    }
}

/// `clamp_f3(rgb, 0, max)` with NaN landing on `0`.
#[inline]
fn clamp_nan_to_zero(v: f32, max: f32) -> f32 {
    v.max(0.0).min(max)
}

const TRANSFORM_ID_PREFIX: &str = "urn:ampas:aces:transformId:v2.0:";

/// Every forward `Output.Academy.*` transform ID shipped in
/// <https://github.com/aces-aswf/aces-output> (`main`, 2025-10; 54 presets).
pub const ACES_OUTPUT_TRANSFORM_IDS: [&str; 54] = [
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_300nit_in_XYZ-E_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_48nit_in_XYZ-E_Gamma2pt6.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_1000nit_in_P3-D65_sRGB-Piecewise.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_100nit_in_P3-D65_Gamma2pt2.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_100nit_in_P3-D65_sRGB-Piecewise.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D60_100nit_in_P3-D65_sRGB-Piecewise.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_1000nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_108nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_2000nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_4000nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_48nit_in_P3-D65_Gamma2pt6.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_500nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D60_100nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D60_48nit_in_P3-D65_Gamma2pt6.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_1000nit_in_Rec2100-D65_HLG.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_1000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_2000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_4000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_500nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D60_1000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D60_2000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D60_4000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D60_500nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D60_100nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D60_100nit_in_Rec709-D65_BT1886.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D60_100nit_in_Rec709-D65_Gamma2pt2.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D60_100nit_in_Rec709-D65_sRGB-Piecewise.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_300nit_in_XYZ-E_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_48nit_in_XYZ-E_Gamma2pt6.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_1000nit_in_P3-D65_sRGB-Piecewise.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_100nit_in_P3-D65_Gamma2pt2.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_100nit_in_P3-D65_sRGB-Piecewise.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_100nit_in_P3-D65_sRGB-Piecewise.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_1000nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_108nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_2000nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_4000nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_48nit_in_P3-D65_Gamma2pt6.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_500nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_100nit_in_P3-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_48nit_in_P3-D65_Gamma2pt6.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_1000nit_in_Rec2100-D65_HLG.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_1000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_2000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_4000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_500nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D65_1000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D65_2000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D65_4000nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D65_500nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_100nit_in_Rec2100-D65_ST2084.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_100nit_in_Rec709-D65_BT1886.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_100nit_in_Rec709-D65_Gamma2pt2.a2.v1",
    "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_100nit_in_Rec709-D65_sRGB-Piecewise.a2.v1",
];

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec::Vec;

    const DISPLAY_CSV: &str =
        include_str!("../../reference-checks/golden/aces2_ocio_display_encoding.csv");
    const DISPLAY_INV_CSV: &str =
        include_str!("../../reference-checks/golden/aces2_ocio_display_encoding_inv.csv");

    fn rows(csv: &str) -> Vec<Vec<&str>> {
        csv.lines()
            .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
            .map(|l| l.split(',').collect())
            .collect()
    }

    fn f(s: &str) -> f32 {
        s.trim()
            .parse()
            .unwrap_or_else(|_| panic!("bad float {s:?}"))
    }

    /// The golden presets, as (config, encoding) pairs.
    fn preset(name: &str) -> (Aces2Config, Aces2DisplayEncoding) {
        let cfg = |peak, prims| Aces2Config {
            peak_luminance: peak,
            limiting_primaries: prims,
        };
        match name {
            "rec709_100_srgb" => (
                cfg(100.0, Chromaticities::REC709),
                Aces2DisplayEncoding::SRGB,
            ),
            "rec709_100_bt1886" => (
                cfg(100.0, Chromaticities::REC709),
                Aces2DisplayEncoding::REC709_BT1886,
            ),
            "rec709_100_g22" => (
                cfg(100.0, Chromaticities::REC709),
                Aces2DisplayEncoding::REC709_GAMMA22,
            ),
            "p3d65_100_g26" => (
                cfg(100.0, Chromaticities::P3_D65),
                Aces2DisplayEncoding::P3_D65_GAMMA26,
            ),
            "p3d65_1000_pq" => (
                cfg(1000.0, Chromaticities::P3_D65),
                Aces2DisplayEncoding::P3_D65_ST2084,
            ),
            "rec2020_1000_pq" => (
                cfg(1000.0, Chromaticities::REC2020),
                Aces2DisplayEncoding::REC2100_ST2084,
            ),
            "p3d65_1000_hlg_rec2100" => (
                cfg(1000.0, Chromaticities::P3_D65),
                Aces2DisplayEncoding::REC2100_HLG,
            ),
            "rec709d60_100_srgb" => (
                cfg(100.0, Chromaticities::REC709_D60),
                Aces2DisplayEncoding::SRGB.with_white_scaling(),
            ),
            "p3d60_1000_pq_rec2100" => (
                cfg(1000.0, Chromaticities::P3_D60),
                Aces2DisplayEncoding::REC2100_ST2084.with_white_scaling(),
            ),
            other => panic!("unknown preset {other}"),
        }
    }

    fn transforms(csv: &str) -> Vec<(&str, Aces2DisplayTransform)> {
        let mut out: Vec<(&str, Aces2DisplayTransform)> = Vec::new();
        for r in rows(csv) {
            if out.iter().all(|(n, _)| *n != r[0]) {
                let (cfg, enc) = preset(r[0]);
                out.push((r[0], Aces2DisplayTransform::new(cfg, enc).unwrap()));
            }
        }
        out
    }

    #[test]
    fn display_encoding_matches_ocio() {
        let ts = transforms(DISPLAY_CSV);
        let mut checked = 0;
        for r in rows(DISPLAY_CSV) {
            let t = &ts.iter().find(|(n, _)| *n == r[0]).unwrap().1;
            let aces = [f(r[1]), f(r[2]), f(r[3])];
            let want = [f(r[4]), f(r[5]), f(r[6])];
            let got = t.forward(aces);
            for c in 0..3 {
                // Code values are in [0, 1]; the rendering agrees with OCIO
                // to ~1e-3 display-linear, which the inverse EOTFs stretch
                // near black (sRGB's linear toe ×12.9, PQ's steep foot).
                assert!(
                    (got[c] - want[c]).abs() <= 3e-3,
                    "{} {aces:?}: {got:?} vs {want:?}",
                    r[0]
                );
            }
            checked += 1;
        }
        assert!(checked >= 200, "only {checked} rows compared");
    }

    #[test]
    fn display_decoding_matches_ocio() {
        let ts = transforms(DISPLAY_INV_CSV);
        let mut checked = 0;
        let mut skipped = 0;
        for r in rows(DISPLAY_INV_CSV) {
            let t = &ts.iter().find(|(n, _)| *n == r[0]).unwrap().1;
            let cv = [f(r[1]), f(r[2]), f(r[3])];
            let want = [f(r[4]), f(r[5]), f(r[6])];
            // OpenColorIO's HLG display is a LUT around its own HLG curve
            // (input scaled so the OETF is `sqrt(x)`), which decodes
            // near-black code values differently from the CTL formula:
            // measured 30% relative disagreement at cv ≈ 0.002 (display
            // linear ~1e-6, i.e. 1e-4 cd/m²) with identical display-linear
            // input fed to both. Those rows are skipped, and counted.
            if t.encoding().eotf == DisplayEotf::Hlg && cv.iter().all(|&c| c < 0.005) {
                skipped += 1;
                continue;
            }
            let got = t.inverse(cv);
            // Same conditioning story as the rendering's inverse test:
            // relative to the pixel magnitude, loose where the forward
            // saturated (peak white, channels pinned at zero).
            let scale = want.iter().fold(1e-3f32, |m, v| m.max(v.abs()));
            for c in 0..3 {
                assert!(
                    (got[c] - want[c]).abs() <= 2e-2 * scale,
                    "{} cv {cv:?}: inverse {got:?} vs {want:?}",
                    r[0]
                );
            }
            checked += 1;
        }
        assert!(checked >= 200, "only {checked} rows compared");
        assert!(skipped <= 3, "{skipped} near-black HLG rows skipped");
    }

    #[test]
    fn eotf_pairs_round_trip() {
        let all = [
            DisplayEotf::Linear,
            DisplayEotf::St2084,
            DisplayEotf::Hlg,
            DisplayEotf::Gamma26,
            DisplayEotf::Bt1886,
            DisplayEotf::Gamma22,
            DisplayEotf::SrgbPiecewise,
        ];
        for eotf in all {
            for i in 0..=200 {
                let lin = i as f32 / 200.0
                    * if eotf == DisplayEotf::St2084 {
                        100.0
                    } else {
                        1.0
                    };
                let cv = eotf.encode(lin);
                assert!((0.0..=1.0001).contains(&cv), "{eotf:?}({lin}) = {cv}");
                let back = eotf.decode(cv);
                assert!(
                    (back - lin).abs() <= 1e-4 + lin * 2e-4,
                    "{eotf:?}: {lin} -> {cv} -> {back}"
                );
            }
            // Negative display-linear clamps to 0 first (PQ's code value for
            // 0 cd/m² is c1^m2 ≈ 7e-7, not 0).
            assert_eq!(eotf.encode(-0.5), eotf.encode(0.0), "{eotf:?}");
        }
        // Anchors: sRGB 0.5 code value ≈ 0.2140 linear; PQ 100 nits = 0.508.
        assert!((DisplayEotf::SrgbPiecewise.decode(0.5) - 0.214_041).abs() < 1e-5);
        assert!((DisplayEotf::St2084.encode(1.0) - 0.508_078).abs() < 1e-5);
    }

    #[test]
    fn white_scaling_fits_d60_white_into_d65_display() {
        // Rec709-D60 limiting, encoded in Rec709-D65 with scaling: the
        // creative white (1,1,1) must land with its largest channel at
        // exactly 1.0 and no channel above it.
        let t = Aces2DisplayTransform::new(
            Aces2Config {
                peak_luminance: 100.0,
                limiting_primaries: Chromaticities::REC709_D60,
            },
            Aces2DisplayEncoding::SRGB.with_white_scaling(),
        )
        .unwrap();
        let cv = t.encode_display([1.0; 3]);
        let max = cv[0].max(cv[1]).max(cv[2]);
        assert!((max - 1.0).abs() < 1e-5, "{cv:?}");
        assert!(cv.iter().all(|&c| c <= 1.0 + 1e-6), "{cv:?}");
        // D60 white is warmer than D65: red above blue.
        assert!(cv[0] > cv[2], "{cv:?}");
        // Without scaling the red channel would clip above 1.0 in the
        // encoding — the difference the switch exists for.
        let unscaled = Aces2DisplayTransform::new(*t.config(), Aces2DisplayEncoding::SRGB).unwrap();
        let raw = unscaled.encode_display([1.0; 3]);
        assert!(raw[0] > 1.0 - 1e-6 && raw[2] < 1.0, "{raw:?}");
        // Decoding undoes the scaling.
        let back = t.decode_display(cv);
        assert!(back.iter().all(|&c| (c - 1.0).abs() < 1e-4), "{back:?}");
    }

    #[test]
    fn transform_ids_match_the_shipped_presets() {
        let id = |peak, lim, enc: Aces2DisplayEncoding| {
            Aces2DisplayTransform::new(
                Aces2Config {
                    peak_luminance: peak,
                    limiting_primaries: lim,
                },
                enc,
            )
            .unwrap()
            .transform_id()
        };
        assert_eq!(
            id(100.0, Chromaticities::REC709, Aces2DisplayEncoding::SRGB),
            Some(
                "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec709-D65_100nit_in_Rec709-D65_sRGB-Piecewise.a2.v1"
            )
        );
        assert_eq!(
            id(
                1000.0,
                Chromaticities::P3_D65,
                Aces2DisplayEncoding::REC2100_HLG
            ),
            Some(
                "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_1000nit_in_Rec2100-D65_HLG.a2.v1"
            )
        );
        assert_eq!(
            id(
                4000.0,
                Chromaticities::REC2020_D60,
                Aces2DisplayEncoding::REC2100_ST2084.with_white_scaling()
            ),
            Some(
                "urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2100-D60_4000nit_in_Rec2100-D65_ST2084.a2.v1"
            )
        );
        // DCDM: 48-nit projector = 100-nit tonescale target, 300 = 625.
        assert_eq!(
            id(
                100.0,
                Chromaticities::P3_D65,
                Aces2DisplayEncoding::DCDM_GAMMA26
            ),
            Some(
                "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D65_48nit_in_XYZ-E_Gamma2pt6.a2.v1"
            )
        );
        assert_eq!(
            id(
                625.0,
                Chromaticities::P3_D60,
                Aces2DisplayEncoding::DCDM_ST2084
            ),
            Some(
                "urn:ampas:aces:transformId:v2.0:Output.Academy.P3-D60_300nit_in_XYZ-E_ST2084.a2.v1"
            )
        );
        // Not shipped: 200-nit Rec.709, a D60 limit without white scaling,
        // linear output, AP1 as a display.
        assert_eq!(
            id(200.0, Chromaticities::REC709, Aces2DisplayEncoding::SRGB),
            None
        );
        assert_eq!(
            id(
                100.0,
                Chromaticities::REC709_D60,
                Aces2DisplayEncoding::SRGB
            ),
            None
        );
        assert_eq!(
            id(
                100.0,
                Chromaticities::REC709,
                Aces2DisplayEncoding {
                    eotf: DisplayEotf::Linear,
                    ..Aces2DisplayEncoding::SRGB
                }
            ),
            None
        );
        assert_eq!(
            id(100.0, Chromaticities::AP1, Aces2DisplayEncoding::SRGB),
            None
        );
        // Every listed ID is unique and well-formed.
        for (i, a) in ACES_OUTPUT_TRANSFORM_IDS.iter().enumerate() {
            assert!(
                a.starts_with(TRANSFORM_ID_PREFIX) && a.ends_with(".a2.v1"),
                "{a}"
            );
            assert!(
                ACES_OUTPUT_TRANSFORM_IDS[..i].iter().all(|b| b != a),
                "duplicate {a}"
            );
        }
    }

    #[test]
    fn rejects_bad_encoding() {
        let cfg = Aces2Config::default();
        for scale in [0.0, -1.0, f32::NAN, f32::INFINITY] {
            let enc = Aces2DisplayEncoding {
                linear_scale: scale,
                ..Aces2DisplayEncoding::SRGB
            };
            assert!(
                Aces2DisplayTransform::new(cfg, enc).is_err(),
                "scale {scale}"
            );
        }
        let degenerate = Aces2DisplayEncoding {
            encoding_primaries: Chromaticities {
                red: [0.3, 0.3],
                green: [0.3, 0.3],
                blue: [0.3, 0.3],
                white: [0.3127, 0.3290],
            },
            ..Aces2DisplayEncoding::SRGB
        };
        assert!(Aces2DisplayTransform::new(cfg, degenerate).is_err());
        // Mismatched rendering / config.
        let ot = Aces2OutputTransform::new(Aces2Config {
            peak_luminance: 1000.0,
            ..cfg
        })
        .unwrap();
        assert!(
            Aces2DisplayTransform::from_output_transform(ot, cfg, Aces2DisplayEncoding::SRGB)
                .is_err()
        );
    }

    #[test]
    fn hostile_input_stays_finite() {
        let t =
            Aces2DisplayTransform::new(Aces2Config::default(), Aces2DisplayEncoding::SRGB).unwrap();
        for rgb in [
            [f32::NAN, 0.5, 0.5],
            [f32::INFINITY, 0.0, 0.0],
            [-1.0e30, 1.0e30, 0.0],
            [f32::MAX, f32::MIN, 0.0],
        ] {
            let out = t.forward(rgb);
            assert!(
                out.iter()
                    .all(|&c| c.is_finite() && (0.0..=1.0).contains(&c)),
                "{rgb:?} -> {out:?}"
            );
            let back = t.inverse(rgb);
            assert!(back.iter().all(|c| c.is_finite()), "{rgb:?} -> {back:?}");
        }
        // Trait dispatch is the encoded forward.
        assert_eq!(ToneMap::map_rgb(&t, [0.18; 3]), t.forward([0.18; 3]));
    }
}
